// translate.js
const translations = {
    en: {
        // Login Page
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "confirm_password": "Confirm Password",
        "payment_password": "Payment Password",
        "referral_code": "Referral Code",
        "optional": "optional",
        "enter_username": "Enter username",
        "enter_password": "Enter password",
        "enter_email": "Enter email",
        "enter_payment_password": "Enter payment password",
        "enter_referral_code": "Enter referral code",
        "password_length_error": "Password must be at least 6 characters",
        "passwords_dont_match": "Passwords don't match",
        "payment_password_length_error": "Payment password must be at least 4 characters",
        "enter_username_error": "Enter username",
        "enter_password_error": "Enter password",
        "enter_email_error": "Enter email",
        "invalid_credentials": "Invalid login credentials",
        "login_error": "Login error occurred. Please try again.",
        "registration_bonus": "Congratulations! You received 3.00 USDT registration bonus!",
        "registration_error": "Registration error occurred. Please try again.",
        "username_exists": "Username or email already exists",
        "invalid_referral": "Invalid referral code",
        
        // Dashboard
        "home": "Home",
        "vip": "VIP",
        "assets": "Assets",
        "profile": "Profile",
        "deposit": "Deposit",
        "withdraw": "Withdraw",
        "team": "Team",
        "task_center": "Task Center",
        "invite_friends": "Invite Friends",
        "history": "History",
        "download": "Download",
        "license": "License",
        "total_balance": "Total Balance",
        "from_referrals": "From Referrals",
        "from_bonuses": "From Bonuses",
        "from_quantification": "From Quantification",
        "available": "Available",
        "transaction_history": "Transaction History",
        "all": "All",
        "deposits": "Deposits",
        "withdrawals": "Withdrawals",
        "referrals": "Referrals",
        "quantification": "Quantification",
        "no_transactions": "No transactions found",
        "loading_transactions": "Loading transactions...",
        "1st_generation": "1st Generation",
        "2nd_generation": "2nd Generation",
        "3rd_generation": "3rd Generation",
        "from_1st_generation": "8% from 1st Generation",
        "from_2nd_generation": "3% from 2nd Generation",
        "from_3rd_generation": "1% from 3rd Generation",
        "loading_referrals": "Loading referrals...",
        "no_referrals": "No referrals yet. Share your referral link to invite friends!",
        "vip_packages": "VIP Packages",
        "vip_package_rules": "VIP Package Rules:",
        "vip_rules_1": "VIP packages are active for exactly 30 days",
        "vip_rules_2": "Daily income: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Package price is returned to your balance after 30 days automatically",
        "vip_rules_4": "Package expires after 30 days - to continue earning, purchase again",
        "vip_rules_5": "You can claim daily income once per day at 22:00 UTC",
        "vip_rules_6": "If you don't claim income today, you can claim it until 22:00 UTC tomorrow",
        "vip_rules_7": "Income doesn't accumulate - use it or lose it!",
        "vip_rules_8": "Higher packages give +0.5% daily income compared to previous level",
        "current_status": "Current Status",
        "purchase_package": "Purchase a package to access premium features",
        "available_for_withdrawal": "Available for withdrawal",
        "today": "today",
        "claim_income": "CLAIM INCOME",
        "no_available_income": "NO AVAILABLE INCOME",
        "already_claimed": "ALREADY CLAIMED",
        "buy_vip_package": "Buy a VIP package to earn income",
        "next_claim": "Next claim",
        "available_for": "Available for",
        "analysis": "Analysis",
        "processing": "Processing",
        "completion": "Completion",
        "change_password": "Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "update_password": "Update Password",
        "identity_verification": "Identity Verification",
        "phone_number": "Phone Number",
        "not_verified": "Not verified",
        "verified": "Verified",
        "verify": "Verify",
        "id_passport": "ID/Passport",
        "logout": "Logout",
        "your_bonuses": "Your Bonuses",
        "how_it_works": "How it works:",
        "referral_works_1": "8% from 1st generation deposits",
        "referral_works_2": "3% from 2nd generation deposits",
        "referral_works_3": "1% from 3rd generation deposits",
        "referral_works_4": "Income credited instantly when referrals purchase VIP packages",
        "available_bonuses": "Available Bonuses",
        "complete_tasks": "Complete tasks and earn additional rewards",
        "task": "Task",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registration Bonus",
        "purchase_vip2": "Purchase VIP 2 Package",
        "purchase_vip3": "Purchase VIP 3 Package",
        "purchase_vip4": "Purchase VIP 4 Package",
        "1st_gen_deposit_50": "1st Generation Deposit 50 USDT",
        "1st_gen_deposit_100": "1st Generation Deposit 100 USDT",
        "1st_gen_deposit_300": "1st Generation Deposit 300 USDT",
        "1st_gen_deposit_1000": "1st Generation Deposit 1000 USDT",
        "completed": "Completed",
        "available_task": "Available",
        "terms_conditions": "Terms & Conditions:",
        "terms_1": "All bonuses are credited manually by administration",
        "terms_2": "VIP purchase bonuses are awarded after successful package activation",
        "terms_3": "Referral deposit bonuses require minimum deposit amounts from 1st generation users",
        "terms_4": "Bonuses are paid in USDT equivalent",
        "terms_5": "Administration reserves the right to modify bonus terms",
        "license_documents": "License & Documents",
        "official_financial_license": "OFFICIAL FINANCIAL LICENSE",
        "certificate_authorization": "Certificate of Authorization",
        "license_number": "License Number",
        "company_name": "Company Name",
        "registration_address": "Registration Address",
        "date_issue": "Date of Issue",
        "valid_until": "Valid Until",
        "regulatory_body": "Regulatory Body",
        "authorized_signature": "Authorized Signature",
        "director_licensing": "Director of Licensing",
        "official_seal": "Official Regulatory Seal",
        "supporting_documents": "Supporting Documents",
        "financial_report": "Financial Report 2024",
        "annual_audit": "Annual Audit Statement",
        "insurance_certificate": "Insurance Certificate",
        "client_fund_protection": "Client Fund Protection",
        "legal_information": "Legal Information",
        "verified_license": "VERIFIED LICENSE • VALID UNTIL 2037",
        "copy": "Copy",
        "copied": "Copied!",
        "logout_confirm": "Are you sure you want to logout?",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "active": "ACTIVE",
        "buy": "BUY"
    },
    es: {
        // Spanish translations
        "login": "Iniciar Sesión",
        "register": "Registrarse",
        "username": "Usuario",
        "password": "Contraseña",
        "email": "Correo Electrónico",
        "confirm_password": "Confirmar Contraseña",
        "payment_password": "Contraseña de Pago",
        "referral_code": "Código de Referido",
        "optional": "opcional",
        "enter_username": "Ingrese usuario",
        "enter_password": "Ingrese contraseña",
        "enter_email": "Ingrese correo electrónico",
        "enter_payment_password": "Ingrese contraseña de pago",
        "enter_referral_code": "Ingrese código de referido",
        "password_length_error": "La contraseña debe tener al menos 6 caracteres",
        "passwords_dont_match": "Las contraseñas no coinciden",
        "payment_password_length_error": "La contraseña de pago debe tener al menos 4 caracteres",
        "enter_username_error": "Ingrese usuario",
        "enter_password_error": "Ingrese contraseña",
        "enter_email_error": "Ingrese correo electrónico",
        "invalid_credentials": "Credenciales de inicio de sesión inválidas",
        "login_error": "Error al iniciar sesión. Por favor, intente nuevamente.",
        "registration_bonus": "¡Felicitaciones! ¡Recibiste 3.00 USDT de bono de registro!",
        "registration_error": "Error en el registro. Por favor, intente nuevamente.",
        "username_exists": "El usuario o correo electrónico ya existe",
        "invalid_referral": "Código de referido inválido",
        
        // Dashboard
        "home": "Inicio",
        "vip": "VIP",
        "assets": "Activos",
        "profile": "Perfil",
        "deposit": "Depositar",
        "withdraw": "Retirar",
        "team": "Equipo",
        "task_center": "Centro de Tareas",
        "invite_friends": "Invitar Amigos",
        "history": "Historial",
        "download": "Descargar",
        "license": "Licencia",
        "total_balance": "Balance Total",
        "from_referrals": "De Referidos",
        "from_bonuses": "De Bonos",
        "from_quantification": "De Cuantificación",
        "available": "Disponible",
        "transaction_history": "Historial de Transacciones",
        "all": "Todo",
        "deposits": "Depósitos",
        "withdrawals": "Retiros",
        "referrals": "Referidos",
        "quantification": "Cuantificación",
        "no_transactions": "No se encontraron transacciones",
        "loading_transactions": "Cargando transacciones...",
        "1st_generation": "1ra Generación",
        "2nd_generation": "2da Generación",
        "3rd_generation": "3ra Generación",
        "from_1st_generation": "8% de 1ra Generación",
        "from_2nd_generation": "3% de 2da Generación",
        "from_3rd_generation": "1% de 3ra Generación",
        "loading_referrals": "Cargando referidos...",
        "no_referrals": "Aún no hay referidos. ¡Comparte tu enlace de referido para invitar amigos!",
        "vip_packages": "Paquetes VIP",
        "vip_package_rules": "Reglas de Paquetes VIP:",
        "vip_rules_1": "Los paquetes VIP están activos exactamente 30 días",
        "vip_rules_2": "Ingreso diario: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "El precio del paquete se devuelve a tu balance después de 30 días automáticamente",
        "vip_rules_4": "El paquete expira después de 30 días - para continuar ganando, compra nuevamente",
        "vip_rules_5": "Puedes reclamar el ingreso diario una vez al día a las 22:00 UTC",
        "vip_rules_6": "Si no reclamas el ingreso hoy, puedes reclamarlo hasta las 22:00 UTC mañana",
        "vip_rules_7": "El ingreso no se acumula - ¡úsalo o piérdelo!",
        "vip_rules_8": "Los paquetes más altos dan +0.5% de ingreso diario comparado con el nivel anterior",
        "current_status": "Estado Actual",
        "purchase_package": "Compra un paquete para acceder a funciones premium",
        "available_for_withdrawal": "Disponible para retiro",
        "today": "hoy",
        "claim_income": "RECLAMAR INGRESO",
        "no_available_income": "NO HAY INGRESO DISPONIBLE",
        "already_claimed": "YA RECLAMADO",
        "buy_vip_package": "Compra un paquete VIP para ganar ingresos",
        "next_claim": "Próximo reclamo",
        "available_for": "Disponible para",
        "analysis": "Análisis",
        "processing": "Procesando",
        "completion": "Finalización",
        "change_password": "Cambiar Contraseña",
        "current_password": "Contraseña Actual",
        "new_password": "Nueva Contraseña",
        "confirm_new_password": "Confirmar Nueva Contraseña",
        "update_password": "Actualizar Contraseña",
        "identity_verification": "Verificación de Identidad",
        "phone_number": "Número de Teléfono",
        "not_verified": "No verificado",
        "verified": "Verificado",
        "verify": "Verificar",
        "id_passport": "ID/Pasaporte",
        "logout": "Cerrar Sesión",
        "your_bonuses": "Tus Bonos",
        "how_it_works": "Cómo funciona:",
        "referral_works_1": "8% de los depósitos de 1ra generación",
        "referral_works_2": "3% de los depósitos de 2da generación",
        "referral_works_3": "1% de los depósitos de 3ra generación",
        "referral_works_4": "Ingreso acreditado instantáneamente cuando los referidos compran paquetes VIP",
        "available_bonuses": "Bonos Disponibles",
        "complete_tasks": "Completa tareas y gana recompensas adicionales",
        "task": "Tarea",
        "bonus": "Bono",
        "status": "Estado",
        "registration_bonus_task": "Bono de Registro",
        "purchase_vip2": "Comprar Paquete VIP 2",
        "purchase_vip3": "Comprar Paquete VIP 3",
        "purchase_vip4": "Comprar Paquete VIP 4",
        "1st_gen_deposit_50": "Depósito de 1ra Generación 50 USDT",
        "1st_gen_deposit_100": "Depósito de 1ra Generación 100 USDT",
        "1st_gen_deposit_300": "Depósito de 1ra Generación 300 USDT",
        "1st_gen_deposit_1000": "Depósito de 1ra Generación 1000 USDT",
        "completed": "Completado",
        "available_task": "Disponible",
        "terms_conditions": "Términos y Condiciones:",
        "terms_1": "Todos los bonos son acreditados manualmente por la administración",
        "terms_2": "Los bonos de compra VIP se otorgan después de la activación exitosa del paquete",
        "terms_3": "Los bonos de depósito de referidos requieren montos mínimos de depósito de usuarios de 1ra generación",
        "terms_4": "Los bonos se pagan en equivalente USDT",
        "terms_5": "La administración se reserva el derecho de modificar los términos de los bonos",
        "license_documents": "Licencia y Documentos",
        "official_financial_license": "LICENCIA FINANCIERA OFICIAL",
        "certificate_authorization": "Certificado de Autorización",
        "license_number": "Número de Licencia",
        "company_name": "Nombre de la Empresa",
        "registration_address": "Dirección de Registro",
        "date_issue": "Fecha de Emisión",
        "valid_until": "Válido Hasta",
        "regulatory_body": "Organismo Regulador",
        "authorized_signature": "Firma Autorizada",
        "director_licensing": "Director de Licencias",
        "official_seal": "Sello Regulatorio Oficial",
        "supporting_documents": "Documentos de Soporte",
        "financial_report": "Reporte Financiero 2024",
        "annual_audit": "Declaración de Auditoría Anual",
        "insurance_certificate": "Certificado de Seguro",
        "client_fund_protection": "Protección de Fondos del Cliente",
        "legal_information": "Información Legal",
        "verified_license": "LICENCIA VERIFICADA • VÁLIDA HASTA 2037",
        "copy": "Copiar",
        "copied": "¡Copiado!",
        "logout_confirm": "¿Estás seguro de que quieres cerrar sesión?",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "active": "ACTIVO",
        "buy": "COMPRAR"
    },
    de: {
        // German translations
        "login": "Anmelden",
        "register": "Registrieren",
        "username": "Benutzername",
        "password": "Passwort",
        "email": "E-Mail",
        "confirm_password": "Passwort bestätigen",
        "payment_password": "Zahlungspasswort",
        "referral_code": "Empfehlungscode",
        "optional": "optional",
        "enter_username": "Benutzername eingeben",
        "enter_password": "Passwort eingeben",
        "enter_email": "E-Mail eingeben",
        "enter_payment_password": "Zahlungspasswort eingeben",
        "enter_referral_code": "Empfehlungscode eingeben",
        "password_length_error": "Passwort muss mindestens 6 Zeichen lang sein",
        "passwords_dont_match": "Passwörter stimmen nicht überein",
        "payment_password_length_error": "Zahlungspasswort muss mindestens 4 Zeichen lang sein",
        "enter_username_error": "Benutzername eingeben",
        "enter_password_error": "Passwort eingeben",
        "enter_email_error": "E-Mail eingeben",
        "invalid_credentials": "Ungültige Anmeldedaten",
        "login_error": "Anmeldefehler aufgetreten. Bitte versuchen Sie es erneut.",
        "registration_bonus": "Herzlichen Glückwunsch! Sie haben 3.00 USDT Registrierungsbonus erhalten!",
        "registration_error": "Registrierungsfehler aufgetreten. Bitte versuchen Sie es erneut.",
        "username_exists": "Benutzername oder E-Mail existiert bereits",
        "invalid_referral": "Ungültiger Empfehlungscode",
        
        // Dashboard
        "home": "Startseite",
        "vip": "VIP",
        "assets": "Vermögen",
        "profile": "Profil",
        "deposit": "Einzahlen",
        "withdraw": "Auszahlen",
        "team": "Team",
        "task_center": "Aufgabencenter",
        "invite_friends": "Freunde einladen",
        "history": "Verlauf",
        "download": "Herunterladen",
        "license": "Lizenz",
        "total_balance": "Gesamtguthaben",
        "from_referrals": "Von Empfehlungen",
        "from_bonuses": "Von Boni",
        "from_quantification": "Von Quantifizierung",
        "available": "Verfügbar",
        "transaction_history": "Transaktionsverlauf",
        "all": "Alle",
        "deposits": "Einzahlungen",
        "withdrawals": "Auszahlungen",
        "referrals": "Empfehlungen",
        "quantification": "Quantifizierung",
        "no_transactions": "Keine Transaktionen gefunden",
        "loading_transactions": "Lade Transaktionen...",
        "1st_generation": "1. Generation",
        "2nd_generation": "2. Generation",
        "3rd_generation": "3. Generation",
        "from_1st_generation": "8% von 1. Generation",
        "from_2nd_generation": "3% von 2. Generation",
        "from_3rd_generation": "1% von 3. Generation",
        "loading_referrals": "Lade Empfehlungen...",
        "no_referrals": "Noch keine Empfehlungen. Teile deinen Empfehlungslink, um Freunde einzuladen!",
        "vip_packages": "VIP-Pakete",
        "vip_package_rules": "VIP-Paket-Regeln:",
        "vip_rules_1": "VIP-Pakete sind genau 30 Tage aktiv",
        "vip_rules_2": "Tägliches Einkommen: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Paketpreis wird nach 30 Tagen automatisch auf Ihr Guthaben zurückerstattet",
        "vip_rules_4": "Paket läuft nach 30 Tagen ab - um weiter zu verdienen, erneut kaufen",
        "vip_rules_5": "Sie können tägliches Einkommen einmal pro Tag um 22:00 UTC abholen",
        "vip_rules_6": "Wenn Sie Einkommen heute nicht abholen, können Sie es bis 22:00 UTC morgen abholen",
        "vip_rules_7": "Einkommen sammelt sich nicht an - nutzen Sie es oder verlieren Sie es!",
        "vip_rules_8": "Höhere Pakete geben +0.5% tägliches Einkommen im Vergleich zur vorherigen Stufe",
        "current_status": "Aktueller Status",
        "purchase_package": "Kaufen Sie ein Paket, um auf Premium-Funktionen zuzugreifen",
        "available_for_withdrawal": "Verfügbar für Auszahlung",
        "today": "heute",
        "claim_income": "EINKOMMEN ABHOLEN",
        "no_available_income": "KEIN VERFÜGBARES EINKOMMEN",
        "already_claimed": "BEREITS ABGEHOLT",
        "buy_vip_package": "Kaufen Sie ein VIP-Paket, um Einkommen zu verdienen",
        "next_claim": "Nächste Abholung",
        "available_for": "Verfügbar für",
        "analysis": "Analyse",
        "processing": "Wird verarbeitet",
        "completion": "Fertigstellung",
        "change_password": "Passwort ändern",
        "current_password": "Aktuelles Passwort",
        "new_password": "Neues Passwort",
        "confirm_new_password": "Neues Passwort bestätigen",
        "update_password": "Passwort aktualisieren",
        "identity_verification": "Identitätsverifizierung",
        "phone_number": "Telefonnummer",
        "not_verified": "Nicht verifiziert",
        "verified": "Verifiziert",
        "verify": "Verifizieren",
        "id_passport": "Ausweis/Reisepass",
        "logout": "Abmelden",
        "your_bonuses": "Ihre Boni",
        "how_it_works": "So funktioniert es:",
        "referral_works_1": "8% von Einzahlungen der 1. Generation",
        "referral_works_2": "3% von Einzahlungen der 2. Generation",
        "referral_works_3": "1% von Einzahlungen der 3. Generation",
        "referral_works_4": "Einkommen sofort gutgeschrieben, wenn Empfehlungen VIP-Pakete kaufen",
        "available_bonuses": "Verfügbare Boni",
        "complete_tasks": "Aufgaben abschließen und zusätzliche Belohnungen verdienen",
        "task": "Aufgabe",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registrierungsbonus",
        "purchase_vip2": "VIP 2 Paket kaufen",
        "purchase_vip3": "VIP 3 Paket kaufen",
        "purchase_vip4": "VIP 4 Paket kaufen",
        "1st_gen_deposit_50": "1. Generation Einzahlung 50 USDT",
        "1st_gen_deposit_100": "1. Generation Einzahlung 100 USDT",
        "1st_gen_deposit_300": "1. Generation Einzahlung 300 USDT",
        "1st_gen_deposit_1000": "1. Generation Einzahlung 1000 USDT",
        "completed": "Abgeschlossen",
        "available_task": "Verfügbar",
        "terms_conditions": "Geschäftsbedingungen:",
        "terms_1": "Alle Boni werden manuell von der Administration gutgeschrieben",
        "terms_2": "VIP-Kaufboni werden nach erfolgreicher Paketaktivierung vergeben",
        "terms_3": "Empfehlungseinzahlungsboni erfordern Mindesteinzahlungsbeträge von Nutzern der 1. Generation",
        "terms_4": "Boni werden in USDT-Äquivalent ausgezahlt",
        "terms_5": "Administration behält sich das Recht vor, Bonusbedingungen zu ändern",
        "license_documents": "Lizenz & Dokumente",
        "official_financial_license": "OFFIZIELLE FINANZLIZENZ",
        "certificate_authorization": "Berechtigungszertifikat",
        "license_number": "Lizenznummer",
        "company_name": "Firmenname",
        "registration_address": "Registrierungsadresse",
        "date_issue": "Ausstellungsdatum",
        "valid_until": "Gültig bis",
        "regulatory_body": "Regulierungsbehörde",
        "authorized_signature": "Autorisierte Unterschrift",
        "director_licensing": "Lizenzierungsdirektor",
        "official_seal": "Offizielles Regierungssiegel",
        "supporting_documents": "Unterstützende Dokumente",
        "financial_report": "Finanzbericht 2024",
        "annual_audit": "Jahresabschlussprüfung",
        "insurance_certificate": "Versicherungszertifikat",
        "client_fund_protection": "Kundengeldabsicherung",
        "legal_information": "Rechtliche Informationen",
        "verified_license": "VERIFIZIERTE LIZENZ • GÜLTIG BIS 2037",
        "copy": "Kopieren",
        "copied": "Kopiert!",
        "logout_confirm": "Sind Sie sicher, dass Sie sich abmelden möchten?",
        "cancel": "Abbrechen",
        "confirm": "Bestätigen",
        "active": "AKTIV",
        "buy": "KAUFEN"
    },
    pl: {
        // Polish translations
        "login": "Zaloguj się",
        "register": "Zarejestruj się",
        "username": "Nazwa użytkownika",
        "password": "Hasło",
        "email": "E-mail",
        "confirm_password": "Potwierdź hasło",
        "payment_password": "Hasło płatności",
        "referral_code": "Kod polecający",
        "optional": "opcjonalnie",
        "enter_username": "Wprowadź nazwę użytkownika",
        "enter_password": "Wprowadź hasło",
        "enter_email": "Wprowadź e-mail",
        "enter_payment_password": "Wprowadź hasło płatności",
        "enter_referral_code": "Wprowadź kod polecający",
        "password_length_error": "Hasło musi mieć co najmniej 6 znaków",
        "passwords_dont_match": "Hasła nie pasują do siebie",
        "payment_password_length_error": "Hasło płatności musi mieć co najmniej 4 znaki",
        "enter_username_error": "Wprowadź nazwę użytkownika",
        "enter_password_error": "Wprowadź hasło",
        "enter_email_error": "Wprowadź e-mail",
        "invalid_credentials": "Nieprawidłowe dane logowania",
        "login_error": "Wystąpił błąd logowania. Proszę spróbować ponownie.",
        "registration_bonus": "Gratulacje! Otrzymałeś 3.00 USDT bonusu rejestracyjnego!",
        "registration_error": "Wystąpił błąd rejestracji. Proszę spróbować ponownie.",
        "username_exists": "Nazwa użytkownika lub e-mail już istnieje",
        "invalid_referral": "Nieprawidłowy kod polecający",
        
        // Dashboard
        "home": "Strona główna",
        "vip": "VIP",
        "assets": "Aktywa",
        "profile": "Profil",
        "deposit": "Wpłata",
        "withdraw": "Wypłata",
        "team": "Zespół",
        "task_center": "Centrum zadań",
        "invite_friends": "Zaproś przyjaciół",
        "history": "Historia",
        "download": "Pobierz",
        "license": "Licencja",
        "total_balance": "Całkowite saldo",
        "from_referrals": "Od poleconych",
        "from_bonuses": "Od bonusów",
        "from_quantification": "Od kwantyfikacji",
        "available": "Dostępne",
        "transaction_history": "Historia transakcji",
        "all": "Wszystko",
        "deposits": "Wpłaty",
        "withdrawals": "Wypłaty",
        "referrals": "Poleceni",
        "quantification": "Kwantyfikacja",
        "no_transactions": "Nie znaleziono transakcji",
        "loading_transactions": "Ładowanie transakcji...",
        "1st_generation": "1. generacja",
        "2nd_generation": "2. generacja",
        "3rd_generation": "3. generacja",
        "from_1st_generation": "8% od 1. generacji",
        "from_2nd_generation": "3% od 2. generacji",
        "from_3rd_generation": "1% od 3. generacji",
        "loading_referrals": "Ładowanie poleconych...",
        "no_referrals": "Jeszcze nie ma poleconych. Udostępnij swój link polecający, aby zaprosić przyjaciół!",
        "vip_packages": "Pakiety VIP",
        "vip_package_rules": "Zasady pakietów VIP:",
        "vip_rules_1": "Pakiety VIP są aktywne dokładnie 30 dni",
        "vip_rules_2": "Dochód dzienny: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Cena pakietu jest zwracana na Twoje saldo po 30 dniach automatycznie",
        "vip_rules_4": "Pakiet wygasa po 30 dniach - aby kontynuować zarabianie, kup ponownie",
        "vip_rules_5": "Możesz odbierać dzienny dochód raz dziennie o 22:00 UTC",
        "vip_rules_6": "Jeśli nie odbierzesz dochodu dziś, możesz go odebrać do 22:00 UTC jutro",
        "vip_rules_7": "Dochód się nie kumuluje - wykorzystaj go lub strać!",
        "vip_rules_8": "Wyższe pakiety dają +0.5% dziennego dochodu w porównaniu do poprzedniego poziomu",
        "current_status": "Aktualny status",
        "purchase_package": "Kup pakiet, aby uzyskać dostęp do funkcji premium",
        "available_for_withdrawal": "Dostępne do wypłaty",
        "today": "dzisiaj",
        "claim_income": "ODBIERZ DOCHÓD",
        "no_available_income": "BRAK DOSTĘPNEGO DOCHODU",
        "already_claimed": "JUŻ ODEBRANE",
        "buy_vip_package": "Kup pakiet VIP, aby zacząć zarabiać",
        "next_claim": "Następny odbiór",
        "available_for": "Dostępne dla",
        "analysis": "Analiza",
        "processing": "Przetwarzanie",
        "completion": "Ukończenie",
        "change_password": "Zmień hasło",
        "current_password": "Aktualne hasło",
        "new_password": "Nowe hasło",
        "confirm_new_password": "Potwierdź nowe hasło",
        "update_password": "Zaktualizuj hasło",
        "identity_verification": "Weryfikacja tożsamości",
        "phone_number": "Numer telefonu",
        "not_verified": "Niezweryfikowany",
        "verified": "Zweryfikowany",
        "verify": "Zweryfikuj",
        "id_passport": "Dowód/Paszport",
        "logout": "Wyloguj się",
        "your_bonuses": "Twoje bonusy",
        "how_it_works": "Jak to działa:",
        "referral_works_1": "8% od depozytów 1. generacji",
        "referral_works_2": "3% od depozytów 2. generacji",
        "referral_works_3": "1% od depozytów 3. generacji",
        "referral_works_4": "Dochód naliczany natychmiast, gdy poleceni kupują pakiety VIP",
        "available_bonuses": "Dostępne bonusy",
        "complete_tasks": "Wykonuj zadania i zdobywaj dodatkowe nagrody",
        "task": "Zadanie",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Bonus rejestracyjny",
        "purchase_vip2": "Kup pakiet VIP 2",
        "purchase_vip3": "Kup pakiet VIP 3",
        "purchase_vip4": "Kup pakiet VIP 4",
        "1st_gen_deposit_50": "Depozyt 1. generacji 50 USDT",
        "1st_gen_deposit_100": "Depozyt 1. generacji 100 USDT",
        "1st_gen_deposit_300": "Depozyt 1. generacji 300 USDT",
        "1st_gen_deposit_1000": "Depozyt 1. generacji 1000 USDT",
        "completed": "Ukończono",
        "available_task": "Dostępne",
        "terms_conditions": "Warunki i zasady:",
        "terms_1": "Wszystkie bonusy są przyznawane ręcznie przez administrację",
        "terms_2": "Bonusy za zakup VIP są przyznawane po udanej aktywacji pakietu",
        "terms_3": "Bonusy za depozyty poleconych wymagają minimalnych kwot depozytów od użytkowników 1. generacji",
        "terms_4": "Bonusy są wypłacane w ekwiwalencie USDT",
        "terms_5": "Administracja zastrzega sobie prawo do modyfikacji warunków bonusów",
        "license_documents": "Licencja i dokumenty",
        "official_financial_license": "OFICJALNA LICENCJA FINANSOWA",
        "certificate_authorization": "Certyfikat autoryzacji",
        "license_number": "Numer licencji",
        "company_name": "Nazwa firmy",
        "registration_address": "Adres rejestracji",
        "date_issue": "Data wydania",
        "valid_until": "Ważny do",
        "regulatory_body": "Organ regulacyjny",
        "authorized_signature": "Autoryzowany podpis",
        "director_licensing": "Dyrektor licencjonowania",
        "official_seal": "Oficjalna pieczęć regulacyjna",
        "supporting_documents": "Dokumenty pomocnicze",
        "financial_report": "Raport finansowy 2024",
        "annual_audit": "Roczne oświadczenie audytowe",
        "insurance_certificate": "Certyfikat ubezpieczenia",
        "client_fund_protection": "Ochrona funduszy klienta",
        "legal_information": "Informacje prawne",
        "verified_license": "ZWIERYFIKOWANA LICENCJA • WAŻNA DO 2037",
        "copy": "Kopiuj",
        "copied": "Skopiowano!",
        "logout_confirm": "Czy na pewno chcesz się wylogować?",
        "cancel": "Anuluj",
        "confirm": "Potwierdź",
        "active": "AKTYWNY",
        "buy": "KUP"
    },
    ru: {
        // Russian translations (already complete in your original code)
        "login": "Войти",
        "register": "Регистрация",
        "username": "Имя пользователя",
        "password": "Пароль",
        "email": "Электронная почта",
        "confirm_password": "Подтвердите пароль",
        "payment_password": "Платежный пароль",
        "referral_code": "Реферальный код",
        "optional": "необязательно",
        "enter_username": "Введите имя пользователя",
        "enter_password": "Введите пароль",
        "enter_email": "Введите электронную почту",
        "enter_payment_password": "Введите платежный пароль",
        "enter_referral_code": "Введите реферальный код",
        "password_length_error": "Пароль должен быть не менее 6 символов",
        "passwords_dont_match": "Пароли не совпадают",
        "payment_password_length_error": "Платежный пароль должен быть не менее 4 символов",
        "enter_username_error": "Введите имя пользователя",
        "enter_password_error": "Введите пароль",
        "enter_email_error": "Введите электронную почту",
        "invalid_credentials": "Неверные учетные данные",
        "login_error": "Ошибка входа. Пожалуйста, попробуйте снова.",
        "registration_bonus": "Поздравляем! Вы получили 3.00 USDT бонус за регистрацию!",
        "registration_error": "Ошибка регистрации. Пожалуйста, попробуйте снова.",
        "username_exists": "Имя пользователя или электронная почта уже существуют",
        "invalid_referral": "Неверный реферальный код",
        
        // Dashboard
        "home": "Главная",
        "vip": "VIP",
        "assets": "Активы",
        "profile": "Профиль",
        "deposit": "Пополнить",
        "withdraw": "Вывести",
        "team": "Команда",
        "task_center": "Центр заданий",
        "invite_friends": "Пригласить друзей",
        "history": "История",
        "download": "Скачать",
        "license": "Лицензия",
        "total_balance": "Общий баланс",
        "from_referrals": "От рефералов",
        "from_bonuses": "От бонусов",
        "from_quantification": "От квантификации",
        "available": "Доступно",
        "transaction_history": "История транзакций",
        "all": "Все",
        "deposits": "Пополнения",
        "withdrawals": "Выводы",
        "referrals": "Рефералы",
        "quantification": "Квантификация",
        "no_transactions": "Транзакции не найдены",
        "loading_transactions": "Загрузка транзакций...",
        "1st_generation": "1-е поколение",
        "2nd_generation": "2-е поколение",
        "3rd_generation": "3-е поколение",
        "from_1st_generation": "8% от 1-го поколения",
        "from_2nd_generation": "3% от 2-го поколения",
        "from_3rd_generation": "1% от 3-го поколения",
        "loading_referrals": "Загрузка рефералов...",
        "no_referrals": "Пока нет рефералов. Поделитесь своей реферальной ссылкой, чтобы пригласить друзей!",
        "vip_packages": "VIP Пакеты",
        "vip_package_rules": "Правила VIP пакетов:",
        "vip_rules_1": "VIP пакеты активны ровно 30 дней",
        "vip_rules_2": "Ежедневный доход: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Стоимость пакета возвращается на ваш баланс через 30 дней автоматически",
        "vip_rules_4": "Пакет истекает через 30 дней - чтобы продолжить зарабатывать, приобретите снова",
        "vip_rules_5": "Вы можете забирать ежедневный доход один раз в день в 22:00 UTC",
        "vip_rules_6": "Если вы не забрали доход сегодня, вы можете забрать его до 22:00 UTC завтра",
        "vip_rules_7": "Доход не накапливается - используйте его или теряйте!",
        "vip_rules_8": "Высшие пакеты дают +0.5% ежедневного дохода по сравнению с предыдущим уровнем",
        "current_status": "Текущий статус",
        "purchase_package": "Приобретите пакет для доступа к премиум функциям",
        "available_for_withdrawal": "Доступно для вывода",
        "today": "сегодня",
        "claim_income": "ЗАБРАТЬ ДОХОД",
        "no_available_income": "НЕТ ДОСТУПНОГО ДОХОДА",
        "already_claimed": "УЖЕ ЗАБРАНО",
        "buy_vip_package": "Купите VIP пакет, чтобы начать зарабатывать",
        "next_claim": "Следующий забор",
        "available_for": "Доступно для",
        "analysis": "Анализ",
        "processing": "Обработка",
        "completion": "Завершение",
        "change_password": "Изменить пароль",
        "current_password": "Текущий пароль",
        "new_password": "Новый пароль",
        "confirm_new_password": "Подтвердите новый пароль",
        "update_password": "Обновить пароль",
        "identity_verification": "Верификация личности",
        "phone_number": "Номер телефона",
        "not_verified": "Не верифицирован",
        "verified": "Верифицирован",
        "verify": "Верифицировать",
        "id_passport": "ID/Паспорт",
        "logout": "Выйти",
        "your_bonuses": "Ваши бонусы",
        "how_it_works": "Как это работает:",
        "referral_works_1": "8% от депозитов 1-го поколения",
        "referral_works_2": "3% от депозитов 2-го поколения",
        "referral_works_3": "1% от депозитов 3-го поколения",
        "referral_works_4": "Доход зачисляется мгновенно, когда рефералы покупают VIP пакеты",
        "available_bonuses": "Доступные бонусы",
        "complete_tasks": "Выполняйте задания и получайте дополнительные награды",
        "task": "Задание",
        "bonus": "Бонус",
        "status": "Статус",
        "registration_bonus_task": "Бонус за регистрацию",
        "purchase_vip2": "Покупка VIP 2 Пакета",
        "purchase_vip3": "Покупка VIP 3 Пакета",
        "purchase_vip4": "Покупка VIP 4 Пакета",
        "1st_gen_deposit_50": "Депозит 1-го поколения 50 USDT",
        "1st_gen_deposit_100": "Депозит 1-го поколения 100 USDT",
        "1st_gen_deposit_300": "Депозит 1-го поколения 300 USDT",
        "1st_gen_deposit_1000": "Депозит 1-го поколения 1000 USDT",
        "completed": "Выполнено",
        "available_task": "Доступно",
        "terms_conditions": "Условия и положения:",
        "terms_1": "Все бонусы зачисляются вручную администрацией",
        "terms_2": "Бонусы за покупку VIP начисляются после успешной активации пакета",
        "terms_3": "Бонусы за депозиты рефералов требуют минимальных сумм депозитов от пользователей 1-го поколения",
        "terms_4": "Бонусы выплачиваются в эквиваленте USDT",
        "terms_5": "Администрация оставляет за собой право изменять условия бонусов",
        "license_documents": "Лицензия и Документы",
        "official_financial_license": "ОФИЦИАЛЬНАЯ ФИНАНСОВАЯ ЛИЦЕНЗИЯ",
        "certificate_authorization": "Сертификат Авторизации",
        "license_number": "Номер лицензии",
        "company_name": "Название компании",
        "registration_address": "Адрес регистрации",
        "date_issue": "Дата выдачи",
        "valid_until": "Действительна до",
        "regulatory_body": "Регулирующий орган",
        "authorized_signature": "Авторизованная подпись",
        "director_licensing": "Директор по лицензированию",
        "official_seal": "Официальная печать регулятора",
        "supporting_documents": "Поддерживающие документы",
        "financial_report": "Финансовый отчет 2024",
        "annual_audit": "Годовой аудиторский отчет",
        "insurance_certificate": "Сертификат страхования",
        "client_fund_protection": "Защита клиентских средств",
        "legal_information": "Юридическая информация",
        "verified_license": "ПРОВЕРЕННАЯ ЛИЦЕНЗИЯ • ДЕЙСТВИТЕЛЬНА ДО 2037",
        "copy": "Копировать",
        "copied": "Скопировано!",
        "logout_confirm": "Вы уверены, что хотите выйти?",
        "cancel": "Отмена",
        "confirm": "Подтвердить",
        "active": "АКТИВНО",
        "buy": "КУПИТЬ"
    },
    tr: {
        // Turkish translations
        "login": "Giriş Yap",
        "register": "Kayıt Ol",
        "username": "Kullanıcı Adı",
        "password": "Şifre",
        "email": "E-posta",
        "confirm_password": "Şifreyi Onayla",
        "payment_password": "Ödeme Şifresi",
        "referral_code": "Referans Kodu",
        "optional": "isteğe bağlı",
        "enter_username": "Kullanıcı adını girin",
        "enter_password": "Şifreyi girin",
        "enter_email": "E-postayı girin",
        "enter_payment_password": "Ödeme şifresini girin",
        "enter_referral_code": "Referans kodunu girin",
        "password_length_error": "Şifre en az 6 karakter olmalıdır",
        "passwords_dont_match": "Şifreler eşleşmiyor",
        "payment_password_length_error": "Ödeme şifresi en az 4 karakter olmalıdır",
        "enter_username_error": "Kullanıcı adını girin",
        "enter_password_error": "Şifreyi girin",
        "enter_email_error": "E-postayı girin",
        "invalid_credentials": "Geçersiz giriş bilgileri",
        "login_error": "Giriş hatası oluştu. Lütfen tekrar deneyin.",
        "registration_bonus": "Tebrikler! 3.00 USDT kayıt bonusu aldınız!",
        "registration_error": "Kayıt hatası oluştu. Lütfen tekrar deneyin.",
        "username_exists": "Kullanıcı adı veya e-posta zaten var",
        "invalid_referral": "Geçersiz referans kodu",
        
        // Dashboard
        "home": "Ana Sayfa",
        "vip": "VIP",
        "assets": "Varlıklar",
        "profile": "Profil",
        "deposit": "Yatır",
        "withdraw": "Çek",
        "team": "Takım",
        "task_center": "Görev Merkezi",
        "invite_friends": "Arkadaşları Davet Et",
        "history": "Geçmiş",
        "download": "İndir",
        "license": "Lisans",
        "total_balance": "Toplam Bakiye",
        "from_referrals": "Referanslardan",
        "from_bonuses": "Bonuslardan",
        "from_quantification": "Kantifikasyondan",
        "available": "Mevcut",
        "transaction_history": "İşlem Geçmişi",
        "all": "Tümü",
        "deposits": "Yatırımlar",
        "withdrawals": "Çekimler",
        "referrals": "Referanslar",
        "quantification": "Kantifikasyon",
        "no_transactions": "İşlem bulunamadı",
        "loading_transactions": "İşlemler yükleniyor...",
        "1st_generation": "1. Nesil",
        "2nd_generation": "2. Nesil",
        "3rd_generation": "3. Nesil",
        "from_1st_generation": "1. Nesilden %8",
        "from_2nd_generation": "2. Nesilden %3",
        "from_3rd_generation": "3. Nesilden %1",
        "loading_referrals": "Referanslar yükleniyor...",
        "no_referrals": "Henüz referans yok. Arkadaşlarınızı davet etmek için referans linkinizi paylaşın!",
        "vip_packages": "VIP Paketleri",
        "vip_package_rules": "VIP Paket Kuralları:",
        "vip_rules_1": "VIP paketleri tam 30 gün aktiftir",
        "vip_rules_2": "Günlük gelir: VIP1: %2.6 (0.52 USDT) | VIP2: %3.1 (3.10 USDT) | VIP3: %3.6 (10.80 USDT) | VIP4: %4.1 (41.00 USDT) | VIP5: %4.6 (138.00 USDT) | VIP6: %5.1 (255.00 USDT)",
        "vip_rules_3": "Paket fiyatı 30 gün sonra otomatik olarak bakiyenize iade edilir",
        "vip_rules_4": "Paket 30 gün sonra sona erer - kazanmaya devam etmek için tekrar satın alın",
        "vip_rules_5": "Günlük geliri günde bir kez 22:00 UTC'de talep edebilirsiniz",
        "vip_rules_6": "Bugün geliri talep etmezseniz, yarın 22:00 UTC'ye kadar talep edebilirsiniz",
        "vip_rules_7": "Gelir birikmez - kullanın veya kaybedin!",
        "vip_rules_8": "Daha yüksek paketler önceki seviyeye göre +%0.5 günlük gelir sağlar",
        "current_status": "Mevcut Durum",
        "purchase_package": "Premium özelliklere erişmek için bir paket satın alın",
        "available_for_withdrawal": "Çekim için mevcut",
        "today": "bugün",
        "claim_income": "GELİR TALEP ET",
        "no_available_income": "MEVCUT GELİR YOK",
        "already_claimed": "ZATEN TALEP EDİLDİ",
        "buy_vip_package": "Gelir elde etmek için bir VIP paketi satın alın",
        "next_claim": "Sonraki talep",
        "available_for": "İçin mevcut",
        "analysis": "Analiz",
        "processing": "İşleniyor",
        "completion": "Tamamlanma",
        "change_password": "Şifreyi Değiştir",
        "current_password": "Mevcut Şifre",
        "new_password": "Yeni Şifre",
        "confirm_new_password": "Yeni Şifreyi Onayla",
        "update_password": "Şifreyi Güncelle",
        "identity_verification": "Kimlik Doğrulama",
        "phone_number": "Telefon Numarası",
        "not_verified": "Doğrulanmadı",
        "verified": "Doğrulandı",
        "verify": "Doğrula",
        "id_passport": "Kimlik/Pasaport",
        "logout": "Çıkış Yap",
        "your_bonuses": "Bonuslarınız",
        "how_it_works": "Nasıl çalışır:",
        "referral_works_1": "1. nesil yatırımlardan %8",
        "referral_works_2": "2. nesil yatırımlardan %3",
        "referral_works_3": "3. nesil yatırımlardan %1",
        "referral_works_4": "Referanslar VIP paketleri satın aldığında gelir anında tahsil edilir",
        "available_bonuses": "Mevcut Bonuslar",
        "complete_tasks": "Görevleri tamamlayın ve ek ödüller kazanın",
        "task": "Görev",
        "bonus": "Bonus",
        "status": "Durum",
        "registration_bonus_task": "Kayıt Bonusu",
        "purchase_vip2": "VIP 2 Paketi Satın Al",
        "purchase_vip3": "VIP 3 Paketi Satın Al",
        "purchase_vip4": "VIP 4 Paketi Satın Al",
        "1st_gen_deposit_50": "1. Nesil Yatırım 50 USDT",
        "1st_gen_deposit_100": "1. Nesil Yatırım 100 USDT",
        "1st_gen_deposit_300": "1. Nesil Yatırım 300 USDT",
        "1st_gen_deposit_1000": "1. Nesil Yatırım 1000 USDT",
        "completed": "Tamamlandı",
        "available_task": "Mevcut",
        "terms_conditions": "Şartlar ve Koşullar:",
        "terms_1": "Tüm bonuslar yönetim tarafından manuel olarak tahsil edilir",
        "terms_2": "VIP satın alma bonusları başarılı paket aktivasyonundan sonra verilir",
        "terms_3": "Referans yatırım bonusları 1. nesil kullanıcılardan minimum yatırım tutarları gerektirir",
        "terms_4": "Bonuslar USDT eşdeğerinde ödenir",
        "terms_5": "Yönetim bonus şartlarını değiştirme hakkını saklı tutar",
        "license_documents": "Lisans ve Belgeler",
        "official_financial_license": "RESMİ FİNANSAL LİSANS",
        "certificate_authorization": "Yetki Sertifikası",
        "license_number": "Lisans Numarası",
        "company_name": "Şirket Adı",
        "registration_address": "Kayıt Adresi",
        "date_issue": "Veriliş Tarihi",
        "valid_until": "Geçerlilik Tarihi",
        "regulatory_body": "Düzenleyici Kurum",
        "authorized_signature": "Yetkili İmza",
        "director_licensing": "Lisanslama Müdürü",
        "official_seal": "Resmi Düzenleyici Mühür",
        "supporting_documents": "Destekleyici Belgeler",
        "financial_report": "2024 Finansal Rapor",
        "annual_audit": "Yıllık Denetim Raporu",
        "insurance_certificate": "Sigorta Sertifikası",
        "client_fund_protection": "Müşteri Fonu Koruması",
        "legal_information": "Yasal Bilgiler",
        "verified_license": "DOĞRULANMIŞ LİSANS • 2037'YE KADAR GEÇERLİ",
        "copy": "Kopyala",
        "copied": "Kopyalandı!",
        "logout_confirm": "Çıkış yapmak istediğinizden emin misiniz?",
        "cancel": "İptal",
        "confirm": "Onayla",
        "active": "AKTİF",
        "buy": "SATIN AL"
    },
    ar: {
        // Arabic translations
        "login": "تسجيل الدخول",
        "register": "تسجيل",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "email": "البريد الإلكتروني",
        "confirm_password": "تأكيد كلمة المرور",
        "payment_password": "كلمة مرور الدفع",
        "referral_code": "كود الإحالة",
        "optional": "اختياري",
        "enter_username": "أدخل اسم المستخدم",
        "enter_password": "أدخل كلمة المرور",
        "enter_email": "أدخل البريد الإلكتروني",
        "enter_payment_password": "أدخل كلمة مرور الدفع",
        "enter_referral_code": "أدخل كود الإحالة",
        "password_length_error": "يجب أن تكون كلمة المرور至少 6 أحرف",
        "passwords_dont_match": "كلمات المرور غير متطابقة",
        "payment_password_length_error": "يجب أن تكون كلمة مرور الدفع至少 4 أحرف",
        "enter_username_error": "أدخل اسم المستخدم",
        "enter_password_error": "أدخل كلمة المرور",
        "enter_email_error": "أدخل البريد الإلكتروني",
        "invalid_credentials": "بيانات تسجيل الدخول غير صالحة",
        "login_error": "حدث خطأ في تسجيل الدخول. يرجى المحاولة مرة أخرى.",
        "registration_bonus": "مبروك! لقد استلمت 3.00 USDT مكافأة تسجيل!",
        "registration_error": "حدث خطأ في التسجيل. يرجى المحاولة مرة أخرى.",
        "username_exists": "اسم المستخدم أو البريد الإلكتروني موجود بالفعل",
        "invalid_referral": "كود إحالة غير صالح",
        
        // Dashboard
        "home": "الرئيسية",
        "vip": "VIP",
        "assets": "الأصول",
        "profile": "الملف الشخصي",
        "deposit": "إيداع",
        "withdraw": "سحب",
        "team": "الفريق",
        "task_center": "مركز المهام",
        "invite_friends": "دعوة الأصدقاء",
        "history": "السجل",
        "download": "تحميل",
        "license": "الترخيص",
        "total_balance": "الرصيد الإجمالي",
        "from_referrals": "من الإحالات",
        "from_bonuses": "من المكافآت",
        "from_quantification": "من التكميم",
        "available": "متاح",
        "transaction_history": "سجل المعاملات",
        "all": "الكل",
        "deposits": "الودائع",
        "withdrawals": "السحوبات",
        "referrals": "الإحالات",
        "quantification": "التكميم",
        "no_transactions": "لم يتم العثور على معاملات",
        "loading_transactions": "جاري تحميل المعاملات...",
        "1st_generation": "الجيل الأول",
        "2nd_generation": "الجيل الثاني",
        "3rd_generation": "الجيل الثالث",
        "from_1st_generation": "8% من الجيل الأول",
        "from_2nd_generation": "3% من الجيل الثاني",
        "from_3rd_generation": "1% من الجيل الثالث",
        "loading_referrals": "جاري تحميل الإحالات...",
        "no_referrals": "لا توجد إحالات حتى الآن. شارك رابط الإحالة الخاص بك لدعوة الأصدقاء!",
        "vip_packages": "باقات VIP",
        "vip_package_rules": "قواعد باقات VIP:",
        "vip_rules_1": "باقات VIP نشطة لمدة 30 يومًا بالضبط",
        "vip_rules_2": "الدخل اليومي: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "سعر الباقة يعود إلى رصيدك بعد 30 يومًا تلقائيًا",
        "vip_rules_4": "تنتهي الباقة بعد 30 يومًا - لمواصلة الربح، اشترِ مرة أخرى",
        "vip_rules_5": "يمكنك المطالبة بالدخل اليومي مرة واحدة يوميًا في الساعة 22:00 UTC",
        "vip_rules_6": "إذا لم تطالب بالدخل اليوم، يمكنك المطالبة به حتى 22:00 UTC غدًا",
        "vip_rules_7": "الدخل لا يتراكم - استخدمه أو افقده!",
        "vip_rules_8": "الباقات الأعلى تعطي +0.5% دخل يومي مقارنة بالمستوى السابق",
        "current_status": "الحالة الحالية",
        "purchase_package": "اشترِ باقة للوصول إلى الميزات المميزة",
        "available_for_withdrawal": "متاح للسحب",
        "today": "اليوم",
        "claim_income": "المطالبة بالدخل",
        "no_available_income": "لا يوجد دخل متاح",
        "already_claimed": "تم المطالبة بالفعل",
        "buy_vip_package": "اشترِ باقة VIP لتحقيق الدخل",
        "next_claim": "المطالبة التالية",
        "available_for": "متاح لـ",
        "analysis": "التحليل",
        "processing": "قيد المعالجة",
        "completion": "الإكمال",
        "change_password": "تغيير كلمة المرور",
        "current_password": "كلمة المرور الحالية",
        "new_password": "كلمة المرور الجديدة",
        "confirm_new_password": "تأكيد كلمة المرور الجديدة",
        "update_password": "تحديث كلمة المرور",
        "identity_verification": "التحقق من الهوية",
        "phone_number": "رقم الهاتف",
        "not_verified": "غير موثق",
        "verified": "موثق",
        "verify": "تحقق",
        "id_passport": "الهوية/جواز السفر",
        "logout": "تسجيل الخروج",
        "your_bonuses": "مكافآتك",
        "how_it_works": "كيف يعمل:",
        "referral_works_1": "8% من ودائع الجيل الأول",
        "referral_works_2": "3% من ودائع الجيل الثاني",
        "referral_works_3": "1% من ودائع الجيل الثالث",
        "referral_works_4": "الدخل يُضاف فورًا عندما يشترِي المُحالُون باقات VIP",
        "available_bonuses": "المكافآت المتاحة",
        "complete_tasks": "أكمل المهام واكسب مكافآت إضافية",
        "task": "المهمة",
        "bonus": "المكافأة",
        "status": "الحالة",
        "registration_bonus_task": "مكافأة التسجيل",
        "purchase_vip2": "شراء باقة VIP 2",
        "purchase_vip3": "شراء باقة VIP 3",
        "purchase_vip4": "شراء باقة VIP 4",
        "1st_gen_deposit_50": "إيداع الجيل الأول 50 USDT",
        "1st_gen_deposit_100": "إيداع الجيل الأول 100 USDT",
        "1st_gen_deposit_300": "إيداع الجيل الأول 300 USDT",
        "1st_gen_deposit_1000": "إيداع الجيل الأول 1000 USDT",
        "completed": "مكتمل",
        "available_task": "متاح",
        "terms_conditions": "الشروط والأحكام:",
        "terms_1": "جميع المكافآت تُضاف يدويًا من قبل الإدارة",
        "terms_2": "مكافآت شراء VIP تُمنح بعد تفعيل الباقة بنجاح",
        "terms_3": "مكافآت إيداع الإحالات تتطلب حدًا أدنى لمبالغ الإيداع من مستخدمي الجيل الأول",
        "terms_4": "المكافآت تُدفَع بما يعادل USDT",
        "terms_5": "تحتفظ الإدارة بالحق في تعديل شروط المكافآت",
        "license_documents": "الترخيص والمستندات",
        "official_financial_license": "ترخيص مالي رسمي",
        "certificate_authorization": "شهادة التفويض",
        "license_number": "رقم الترخيص",
        "company_name": "اسم الشركة",
        "registration_address": "عنوان التسجيل",
        "date_issue": "تاريخ الإصدار",
        "valid_until": "صالحة حتى",
        "regulatory_body": "الهيئة التنظيمية",
        "authorized_signature": "التوقيع المعتمد",
        "director_licensing": "مدير الترخيص",
        "official_seal": "الختم التنظيمي الرسمي",
        "supporting_documents": "المستندات الداعمة",
        "financial_report": "التقرير المالي 2024",
        "annual_audit": "بيان التدقيق السنوي",
        "insurance_certificate": "شهادة التأمين",
        "client_fund_protection": "حماية أموال العميل",
        "legal_information": "المعلومات القانونية",
        "verified_license": "ترخيص موثق • صالح حتى 2037",
        "copy": "نسخ",
        "copied": "تم النسخ!",
        "logout_confirm": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
        "cancel": "إلغاء",
        "confirm": "تأكيد",
        "active": "نشط",
        "buy": "شراء"
    },
    ro: {
        // Romanian translations
        "login": "Autentificare",
        "register": "Înregistrare",
        "username": "Nume utilizator",
        "password": "Parolă",
        "email": "Email",
        "confirm_password": "Confirmă parola",
        "payment_password": "Parolă de plată",
        "referral_code": "Cod de recomandare",
        "optional": "opțional",
        "enter_username": "Introduceți numele de utilizator",
        "enter_password": "Introduceți parola",
        "enter_email": "Introduceți emailul",
        "enter_payment_password": "Introduceți parola de plată",
        "enter_referral_code": "Introduceți codul de recomandare",
        "password_length_error": "Parola trebuie să aibă至少 6 caractere",
        "passwords_dont_match": "Parolele nu se potrivesc",
        "payment_password_length_error": "Parola de plată trebuie să aibă至少 4 caractere",
        "enter_username_error": "Introduceți numele de utilizator",
        "enter_password_error": "Introduceți parola",
        "enter_email_error": "Introduceți emailul",
        "invalid_credentials": "Date de autentificare invalide",
        "login_error": "A apărut o eroare la autentificare. Vă rugăm să încercați din nou.",
        "registration_bonus": "Felicitări! Ați primit 3.00 USDT bonus de înregistrare!",
        "registration_error": "A apărut o eroare la înregistrare. Vă rugăm să încercați din nou.",
        "username_exists": "Numele de utilizator sau emailul există deja",
        "invalid_referral": "Cod de recomandare invalid",
        
        // Dashboard
        "home": "Acasă",
        "vip": "VIP",
        "assets": "Active",
        "profile": "Profil",
        "deposit": "Depune",
        "withdraw": "Retrage",
        "team": "Echipă",
        "task_center": "Centru de sarcini",
        "invite_friends": "Invită prieteni",
        "history": "Istoric",
        "download": "Descarcă",
        "license": "Licență",
        "total_balance": "Sold total",
        "from_referrals": "De la recomandări",
        "from_bonuses": "De la bonusuri",
        "from_quantification": "De la cuantificare",
        "available": "Disponibil",
        "transaction_history": "Istoric tranzacții",
        "all": "Toate",
        "deposits": "Depuneri",
        "withdrawals": "Retrageri",
        "referrals": "Recomandări",
        "quantification": "Cuantificare",
        "no_transactions": "Nu s-au găsit tranzacții",
        "loading_transactions": "Se încarcă tranzacțiile...",
        "1st_generation": "Generația 1",
        "2nd_generation": "Generația 2",
        "3rd_generation": "Generația 3",
        "from_1st_generation": "8% de la generația 1",
        "from_2nd_generation": "3% de la generația 2",
        "from_3rd_generation": "1% de la generația 3",
        "loading_referrals": "Se încarcă recomandările...",
        "no_referrals": "Încă nu există recomandări. Distribuie linkul tău de recomandare pentru a invita prieteni!",
        "vip_packages": "Pachete VIP",
        "vip_package_rules": "Reguli pachete VIP:",
        "vip_rules_1": "Pachetele VIP sunt active exact 30 de zile",
        "vip_rules_2": "Venit zilnic: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Prețul pachetului este returnat în soldul tău după 30 de zile automat",
        "vip_rules_4": "Pachetul expiră după 30 de zile - pentru a continua să câștigi, cumpără din nou",
        "vip_rules_5": "Poți cere venitul zilnic o dată pe zi la 22:00 UTC",
        "vip_rules_6": "Dacă nu ceri venitul astăzi, poți să-l ceri până la 22:00 UTC mâine",
        "vip_rules_7": "Venitul nu se acumulează - folosește-l sau pierde-l!",
        "vip_rules_8": "Pachetele mai mari oferă +0.5% venit zilnic comparativ cu nivelul anterior",
        "current_status": "Stare curentă",
        "purchase_package": "Cumpără un pachet pentru a accesa funcții premium",
        "available_for_withdrawal": "Disponibil pentru retragere",
        "today": "astăzi",
        "claim_income": "CERE VENIT",
        "no_available_income": "NU EXISTĂ VENIT DISPONIBIL",
        "already_claimed": "DEJA SOLICITAT",
        "buy_vip_package": "Cumpără un pachet VIP pentru a câștiga venit",
        "next_claim": "Următoarea cerere",
        "available_for": "Disponibil pentru",
        "analysis": "Analiză",
        "processing": "Procesare",
        "completion": "Finalizare",
        "change_password": "Schimbă parola",
        "current_password": "Parola curentă",
        "new_password": "Parola nouă",
        "confirm_new_password": "Confirmă parola nouă",
        "update_password": "Actualizează parola",
        "identity_verification": "Verificare identitate",
        "phone_number": "Număr de telefon",
        "not_verified": "Neverificat",
        "verified": "Verificat",
        "verify": "Verifică",
        "id_passport": "ID/Pașaport",
        "logout": "Deconectare",
        "your_bonuses": "Bonusurile tale",
        "how_it_works": "Cum funcționează:",
        "referral_works_1": "8% din depozitele generației 1",
        "referral_works_2": "3% din depozitele generației 2",
        "referral_works_3": "1% din depozitele generației 3",
        "referral_works_4": "Venit creditat instant când recomandările cumpără pachete VIP",
        "available_bonuses": "Bonusuri disponibile",
        "complete_tasks": "Finalizează sarcini și câștigă recompense additionale",
        "task": "Sarcină",
        "bonus": "Bonus",
        "status": "Stare",
        "registration_bonus_task": "Bonus de înregistrare",
        "purchase_vip2": "Cumpără Pachet VIP 2",
        "purchase_vip3": "Cumpără Pachet VIP 3",
        "purchase_vip4": "Cumpără Pachet VIP 4",
        "1st_gen_deposit_50": "Depozit generația 1 50 USDT",
        "1st_gen_deposit_100": "Depozit generația 1 100 USDT",
        "1st_gen_deposit_300": "Depozit generația 1 300 USDT",
        "1st_gen_deposit_1000": "Depozit generația 1 1000 USDT",
        "completed": "Finalizat",
        "available_task": "Disponibil",
        "terms_conditions": "Termeni și condiții:",
        "terms_1": "Toate bonusurile sunt creditate manual de administrație",
        "terms_2": "Bonusurile pentru cumpărare VIP sunt acordate după activarea cu succes a pachetului",
        "terms_3": "Bonusurile pentru depozite de recomandare necesită sume minime de depozit de la utilizatorii generației 1",
        "terms_4": "Bonusurile sunt plătite în echivalent USDT",
        "terms_5": "Administrația își rezervă dreptul de a modifica termenii bonusurilor",
        "license_documents": "Licență și Documente",
        "official_financial_license": "LICENȚĂ FINANCIARĂ OFICIALĂ",
        "certificate_authorization": "Certificat de Autorizație",
        "license_number": "Număr licență",
        "company_name": "Nume companie",
        "registration_address": "Adresă de înregistrare",
        "date_issue": "Data emiterii",
        "valid_until": "Valabil până la",
        "regulatory_body": "Organ de reglementare",
        "authorized_signature": "Semnătură autorizată",
        "director_licensing": "Director de licențiere",
        "official_seal": "Sigiliu regulator oficial",
        "supporting_documents": "Documente justificative",
        "financial_report": "Raport financiar 2024",
        "annual_audit": "Raport de audit anual",
        "insurance_certificate": "Certificat de asigurare",
        "client_fund_protection": "Protecția fondurilor clienților",
        "legal_information": "Informații legale",
        "verified_license": "LICENȚĂ VERIFICATĂ • VALABILĂ PÂNĂ ÎN 2037",
        "copy": "Copiază",
        "copied": "Copiat!",
        "logout_confirm": "Sigur doriți să vă deconectați?",
        "cancel": "Anulează",
        "confirm": "Confirmă",
        "active": "ACTIV",
        "buy": "CUMPĂRĂ"
    },
    uk: {
        // Ukrainian translations
        "login": "Увійти",
        "register": "Реєстрація",
        "username": "Ім'я користувача",
        "password": "Пароль",
        "email": "Електронна пошта",
        "confirm_password": "Підтвердіть пароль",
        "payment_password": "Платіжний пароль",
        "referral_code": "Реферальний код",
        "optional": "необов'язково",
        "enter_username": "Введіть ім'я користувача",
        "enter_password": "Введіть пароль",
        "enter_email": "Введіть електронну пошту",
        "enter_payment_password": "Введіть платіжний пароль",
        "enter_referral_code": "Введіть реферальний код",
        "password_length_error": "Пароль повинен містити至少 6 символів",
        "passwords_dont_match": "Паролі не співпадають",
        "payment_password_length_error": "Платіжний пароль повинен містити至少 4 символи",
        "enter_username_error": "Введіть ім'я користувача",
        "enter_password_error": "Введіть пароль",
        "enter_email_error": "Введіть електронну пошту",
        "invalid_credentials": "Невірні облікові дані",
        "login_error": "Помилка входу. Будь ласка, спробуйте ще раз.",
        "registration_bonus": "Вітаємо! Ви отримали 3.00 USDT бонус за реєстрацію!",
        "registration_error": "Помилка реєстрації. Будь ласка, спробуйте ще раз.",
        "username_exists": "Ім'я користувача або електронна пошта вже існують",
        "invalid_referral": "Невірний реферальний код",
        
        // Dashboard
        "home": "Головна",
        "vip": "VIP",
        "assets": "Активи",
        "profile": "Профіль",
        "deposit": "Поповнити",
        "withdraw": "Вивести",
        "team": "Команда",
        "task_center": "Центр завдань",
        "invite_friends": "Запросити друзів",
        "history": "Історія",
        "download": "Завантажити",
        "license": "Ліцензія",
        "total_balance": "Загальний баланс",
        "from_referrals": "Від рефералів",
        "from_bonuses": "Від бонусів",
        "from_quantification": "Від квантифікації",
        "available": "Доступно",
        "transaction_history": "Історія транзакцій",
        "all": "Всі",
        "deposits": "Поповнення",
        "withdrawals": "Виведення",
        "referrals": "Реферали",
        "quantification": "Квантифікація",
        "no_transactions": "Транзакції не знайдено",
        "loading_transactions": "Завантаження транзакцій...",
        "1st_generation": "1-ше покоління",
        "2nd_generation": "2-ге покоління",
        "3rd_generation": "3-тє покоління",
        "from_1st_generation": "8% від 1-го покоління",
        "from_2nd_generation": "3% від 2-го покоління",
        "from_3rd_generation": "1% від 3-го покоління",
        "loading_referrals": "Завантаження рефералів...",
        "no_referrals": "Поки немає рефералів. Поділіться своїм реферальним посиланням, щоб запросити друзів!",
        "vip_packages": "VIP Пакети",
        "vip_package_rules": "Правила VIP пакетів:",
        "vip_rules_1": "VIP пакети активні рівно 30 днів",
        "vip_rules_2": "Щоденний дохід: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Вартість пакету повертається на ваш баланс через 30 днів автоматично",
        "vip_rules_4": "Пакет закінчується через 30 днів - щоб продовжити заробляти, придбайте знову",
        "vip_rules_5": "Ви можете отримувати щоденний дохід один раз на день о 22:00 UTC",
        "vip_rules_6": "Якщо ви не отримали дохід сьогодні, ви можете отримати його до 22:00 UTC завтра",
        "vip_rules_7": "Дохід не накопичується - використовуйте його або втрачайте!",
        "vip_rules_8": "Вищі пакети дають +0.5% щоденного доходу порівняно з попереднім рівнем",
        "current_status": "Поточний статус",
        "purchase_package": "Придбайте пакет для доступу до преміум функцій",
        "available_for_withdrawal": "Доступно для виведення",
        "today": "сьогодні",
        "claim_income": "ОТРИМАТИ ДОХІД",
        "no_available_income": "НЕМАЄ ДОСТУПНОГО ДОХОДУ",
        "already_claimed": "ВЖЕ ОТРИМАНО",
        "buy_vip_package": "Купіть VIP пакет, щоб почати заробляти",
        "next_claim": "Наступне отримання",
        "available_for": "Доступно для",
        "analysis": "Аналіз",
        "processing": "Обробка",
        "completion": "Завершення",
        "change_password": "Змінити пароль",
        "current_password": "Поточний пароль",
        "new_password": "Новий пароль",
        "confirm_new_password": "Підтвердіть новий пароль",
        "update_password": "Оновити пароль",
        "identity_verification": "Верифікація особи",
        "phone_number": "Номер телефону",
        "not_verified": "Не верифіковано",
        "verified": "Верифіковано",
        "verify": "Верифікувати",
        "id_passport": "ID/Паспорт",
        "logout": "Вийти",
        "your_bonuses": "Ваші бонуси",
        "how_it_works": "Як це працює:",
        "referral_works_1": "8% від депозитів 1-го покоління",
        "referral_works_2": "3% від депозитів 2-го покоління",
        "referral_works_3": "1% від депозитів 3-го покоління",
        "referral_works_4": "Дохід нараховується миттєво, коли реферали купують VIP пакети",
        "available_bonuses": "Доступні бонуси",
        "complete_tasks": "Виконуйте завдання та отримуйте додаткові винагороди",
        "task": "Завдання",
        "bonus": "Бонус",
        "status": "Статус",
        "registration_bonus_task": "Бонус за реєстрацію",
        "purchase_vip2": "Купівля VIP 2 Пакету",
        "purchase_vip3": "Купівля VIP 3 Пакету",
        "purchase_vip4": "Купівля VIP 4 Пакету",
        "1st_gen_deposit_50": "Депозит 1-го покоління 50 USDT",
        "1st_gen_deposit_100": "Депозит 1-го покоління 100 USDT",
        "1st_gen_deposit_300": "Депозит 1-го покоління 300 USDT",
        "1st_gen_deposit_1000": "Депозит 1-го покоління 1000 USDT",
        "completed": "Виконано",
        "available_task": "Доступно",
        "terms_conditions": "Умови та положення:",
        "terms_1": "Усі бонуси нараховуються вручну адміністрацією",
        "terms_2": "Бонуси за покупку VIP нараховуються після успішної активації пакету",
        "terms_3": "Бонуси за депозити рефералів вимагають мінімальних сум депозитів від користувачів 1-го покоління",
        "terms_4": "Бонуси виплачуються в еквіваленті USDT",
        "terms_5": "Адміністрація залишає за собою право змінювати умови бонусів",
        "license_documents": "Ліцензія та Документи",
        "official_financial_license": "ОФІЦІЙНА ФІНАНСОВА ЛІЦЕНЗІЯ",
        "certificate_authorization": "Сертифікат Авторизації",
        "license_number": "Номер ліцензії",
        "company_name": "Назва компанії",
        "registration_address": "Адреса реєстрації",
        "date_issue": "Дата видачі",
        "valid_until": "Дійсна до",
        "regulatory_body": "Регулюючий орган",
        "authorized_signature": "Авторизований підпис",
        "director_licensing": "Директор з ліцензування",
        "official_seal": "Офіційна регуляторна печатка",
        "supporting_documents": "Підтримуючі документи",
        "financial_report": "Фінансовий звіт 2024",
        "annual_audit": "Річний аудиторський звіт",
        "insurance_certificate": "Сертифікат страхування",
        "client_fund_protection": "Захист клієнтських коштів",
        "legal_information": "Юридична інформація",
        "verified_license": "ПЕРЕВІРЕНА ЛІЦЕНЗІЯ • ДІЙСНА ДО 2037",
        "copy": "Копіювати",
        "copied": "Скопійовано!",
        "logout_confirm": "Ви впевнені, що хочете вийти?",
        "cancel": "Скасувати",
        "confirm": "Підтвердити",
        "active": "АКТИВНО",
        "buy": "КУПИТИ"
    },
    fr: {
        // French translations
        "login": "Connexion",
        "register": "S'inscrire",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "email": "E-mail",
        "confirm_password": "Confirmer le mot de passe",
        "payment_password": "Mot de passe de paiement",
        "referral_code": "Code de parrainage",
        "optional": "optionnel",
        "enter_username": "Entrez le nom d'utilisateur",
        "enter_password": "Entrez le mot de passe",
        "enter_email": "Entrez l'e-mail",
        "enter_payment_password": "Entrez le mot de passe de paiement",
        "enter_referral_code": "Entrez le code de parrainage",
        "password_length_error": "Le mot de passe doit contenir至少 6 caractères",
        "passwords_dont_match": "Les mots de passe ne correspondent pas",
        "payment_password_length_error": "Le mot de passe de paiement doit contenir至少 4 caractères",
        "enter_username_error": "Entrez le nom d'utilisateur",
        "enter_password_error": "Entrez le mot de passe",
        "enter_email_error": "Entrez l'e-mail",
        "invalid_credentials": "Identifiants de connexion invalides",
        "login_error": "Une erreur de connexion s'est produite. Veuillez réessayer.",
        "registration_bonus": "Félicitations ! Vous avez reçu 3.00 USDT de bonus d'inscription !",
        "registration_error": "Une erreur d'inscription s'est produite. Veuillez réessayer.",
        "username_exists": "Le nom d'utilisateur ou l'e-mail existe déjà",
        "invalid_referral": "Code de parrainage invalide",
        
        // Dashboard
        "home": "Accueil",
        "vip": "VIP",
        "assets": "Actifs",
        "profile": "Profil",
        "deposit": "Déposer",
        "withdraw": "Retirer",
        "team": "Équipe",
        "task_center": "Centre de tâches",
        "invite_friends": "Inviter des amis",
        "history": "Historique",
        "download": "Télécharger",
        "license": "Licence",
        "total_balance": "Solde total",
        "from_referrals": "Des parrainages",
        "from_bonuses": "Des bonus",
        "from_quantification": "De la quantification",
        "available": "Disponible",
        "transaction_history": "Historique des transactions",
        "all": "Tous",
        "deposits": "Dépôts",
        "withdrawals": "Retraits",
        "referrals": "Parrainages",
        "quantification": "Quantification",
        "no_transactions": "Aucune transaction trouvée",
        "loading_transactions": "Chargement des transactions...",
        "1st_generation": "1ère génération",
        "2nd_generation": "2ème génération",
        "3rd_generation": "3ème génération",
        "from_1st_generation": "8% de la 1ère génération",
        "from_2nd_generation": "3% de la 2ème génération",
        "from_3rd_generation": "1% de la 3ème génération",
        "loading_referrals": "Chargement des parrainages...",
        "no_referrals": "Aucun parrainage pour le moment. Partagez votre lien de parrainage pour inviter des amis !",
        "vip_packages": "Forfaits VIP",
        "vip_package_rules": "Règles des forfaits VIP :",
        "vip_rules_1": "Les forfaits VIP sont actifs exactement 30 jours",
        "vip_rules_2": "Revenu quotidien : VIP1 : 2.6% (0.52 USDT) | VIP2 : 3.1% (3.10 USDT) | VIP3 : 3.6% (10.80 USDT) | VIP4 : 4.1% (41.00 USDT) | VIP5 : 4.6% (138.00 USDT) | VIP6 : 5.1% (255.00 USDT)",
        "vip_rules_3": "Le prix du forfait est retourné à votre solde après 30 jours automatiquement",
        "vip_rules_4": "Le forfait expire après 30 jours - pour continuer à gagner, achetez à nouveau",
        "vip_rules_5": "Vous pouvez réclamer le revenu quotidien une fois par jour à 22:00 UTC",
        "vip_rules_6": "Si vous ne réclamez pas le revenu aujourd'hui, vous pouvez le réclamer jusqu'à 22:00 UTC demain",
        "vip_rules_7": "Le revenu ne s'accumule pas - utilisez-le ou perdez-le !",
        "vip_rules_8": "Les forfaits supérieurs donnent +0.5% de revenu quotidien par rapport au niveau précédent",
        "current_status": "Statut actuel",
        "purchase_package": "Achetez un forfait pour accéder aux fonctionnalités premium",
        "available_for_withdrawal": "Disponible pour retrait",
        "today": "aujourd'hui",
        "claim_income": "RÉCLAMER LE REVENU",
        "no_available_income": "AUCUN REVENU DISPONIBLE",
        "already_claimed": "DÉJÀ RÉCLAMÉ",
        "buy_vip_package": "Achetez un forfait VIP pour gagner un revenu",
        "next_claim": "Prochaine réclamation",
        "available_for": "Disponible pour",
        "analysis": "Analyse",
        "processing": "Traitement",
        "completion": "Achèvement",
        "change_password": "Changer le mot de passe",
        "current_password": "Mot de passe actuel",
        "new_password": "Nouveau mot de passe",
        "confirm_new_password": "Confirmer le nouveau mot de passe",
        "update_password": "Mettre à jour le mot de passe",
        "identity_verification": "Vérification d'identité",
        "phone_number": "Numéro de téléphone",
        "not_verified": "Non vérifié",
        "verified": "Vérifié",
        "verify": "Vérifier",
        "id_passport": "ID/Passeport",
        "logout": "Déconnexion",
        "your_bonuses": "Vos bonus",
        "how_it_works": "Comment ça marche :",
        "referral_works_1": "8% des dépôts de 1ère génération",
        "referral_works_2": "3% des dépôts de 2ème génération",
        "referral_works_3": "1% des dépôts de 3ème génération",
        "referral_works_4": "Revenu crédité instantanément lorsque les filleuls achètent des forfaits VIP",
        "available_bonuses": "Bonus disponibles",
        "complete_tasks": "Terminez des tâches et gagnez des récompenses supplémentaires",
        "task": "Tâche",
        "bonus": "Bonus",
        "status": "Statut",
        "registration_bonus_task": "Bonus d'inscription",
        "purchase_vip2": "Acheter le forfait VIP 2",
        "purchase_vip3": "Acheter le forfait VIP 3",
        "purchase_vip4": "Acheter le forfait VIP 4",
        "1st_gen_deposit_50": "Dépôt 1ère génération 50 USDT",
        "1st_gen_deposit_100": "Dépôt 1ère génération 100 USDT",
        "1st_gen_deposit_300": "Dépôt 1ère génération 300 USDT",
        "1st_gen_deposit_1000": "Dépôt 1ère génération 1000 USDT",
        "completed": "Terminé",
        "available_task": "Disponible",
        "terms_conditions": "Termes et conditions :",
        "terms_1": "Tous les bonus sont crédités manuellement par l'administration",
        "terms_2": "Les bonus d'achat VIP sont attribués après activation réussie du forfait",
        "terms_3": "Les bonus de dépôt de parrainage nécessitent des montants de dépôt minimum des utilisateurs de 1ère génération",
        "terms_4": "Les bonus sont payés en équivalent USDT",
        "terms_5": "L'administration se réserve le droit de modifier les conditions des bonus",
        "license_documents": "Licence et documents",
        "official_financial_license": "LICENCE FINANCIÈRE OFFICIELLE",
        "certificate_authorization": "Certificat d'autorisation",
        "license_number": "Numéro de licence",
        "company_name": "Nom de l'entreprise",
        "registration_address": "Adresse d'enregistrement",
        "date_issue": "Date d'émission",
        "valid_until": "Valable jusqu'au",
        "regulatory_body": "Organisme de réglementation",
        "authorized_signature": "Signature autorisée",
        "director_licensing": "Directeur des licences",
        "official_seal": "Sceau réglementaire officiel",
        "supporting_documents": "Documents justificatifs",
        "financial_report": "Rapport financier 2024",
        "annual_audit": "Déclaration d'audit annuel",
        "insurance_certificate": "Certificat d'assurance",
        "client_fund_protection": "Protection des fonds des clients",
        "legal_information": "Informations légales",
        "verified_license": "LICENCE VÉRIFIÉE • VALABLE JUSQU'EN 2037",
        "copy": "Copier",
        "copied": "Copié !",
        "logout_confirm": "Êtes-vous sûr de vouloir vous déconnecter ?",
        "cancel": "Annuler",
        "confirm": "Confirmer",
        "active": "ACTIF",
        "buy": "ACHETER"
    },
    it: {
        // Italian translations
        "login": "Accedi",
        "register": "Registrati",
        "username": "Nome utente",
        "password": "Password",
        "email": "Email",
        "confirm_password": "Conferma password",
        "payment_password": "Password di pagamento",
        "referral_code": "Codice di referral",
        "optional": "opzionale",
        "enter_username": "Inserisci nome utente",
        "enter_password": "Inserisci password",
        "enter_email": "Inserisci email",
        "enter_payment_password": "Inserisci password di pagamento",
        "enter_referral_code": "Inserisci codice di referral",
        "password_length_error": "La password deve essere di至少 6 caratteri",
        "passwords_dont_match": "Le password non corrispondono",
        "payment_password_length_error": "La password di pagamento deve essere di至少 4 caratteri",
        "enter_username_error": "Inserisci nome utente",
        "enter_password_error": "Inserisci password",
        "enter_email_error": "Inserisci email",
        "invalid_credentials": "Credenziali di accesso non valide",
        "login_error": "Si è verificato un errore di accesso. Riprova.",
        "registration_bonus": "Congratulazioni! Hai ricevuto 3.00 USDT di bonus di registrazione!",
        "registration_error": "Si è verificato un errore di registrazione. Riprova.",
        "username_exists": "Nome utente o email già esistente",
        "invalid_referral": "Codice di referral non valido",
        
        // Dashboard
        "home": "Home",
        "vip": "VIP",
        "assets": "Asset",
        "profile": "Profilo",
        "deposit": "Deposita",
        "withdraw": "Preleva",
        "team": "Team",
        "task_center": "Centro attività",
        "invite_friends": "Invita amici",
        "history": "Cronologia",
        "download": "Scarica",
        "license": "Licenza",
        "total_balance": "Saldo totale",
        "from_referrals": "Da referral",
        "from_bonuses": "Da bonus",
        "from_quantification": "Dalla quantificazione",
        "available": "Disponibile",
        "transaction_history": "Cronologia transazioni",
        "all": "Tutti",
        "deposits": "Depositi",
        "withdrawals": "Prelievi",
        "referrals": "Referral",
        "quantification": "Quantificazione",
        "no_transactions": "Nessuna transazione trovata",
        "loading_transactions": "Caricamento transazioni...",
        "1st_generation": "1a generazione",
        "2nd_generation": "2a generazione",
        "3rd_generation": "3a generazione",
        "from_1st_generation": "8% dalla 1a generazione",
        "from_2nd_generation": "3% dalla 2a generazione",
        "from_3rd_generation": "1% dalla 3a generazione",
        "loading_referrals": "Caricamento referral...",
        "no_referrals": "Ancora nessun referral. Condividi il tuo link di referral per invitare amici!",
        "vip_packages": "Pacchetti VIP",
        "vip_package_rules": "Regole pacchetti VIP:",
        "vip_rules_1": "I pacchetti VIP sono attivi esattamente 30 giorni",
        "vip_rules_2": "Reddito giornaliero: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rules_3": "Il prezzo del pacchetto viene restituito al tuo saldo dopo 30 giorni automaticamente",
        "vip_rules_4": "Il pacchetto scade dopo 30 giorni - per continuare a guadagnare, acquista di nuovo",
        "vip_rules_5": "Puoi ritirare il reddito giornaliero una volta al giorno alle 22:00 UTC",
        "vip_rules_6": "Se non ritiri il reddito oggi, puoi ritirarlo fino alle 22:00 UTC domani",
        "vip_rules_7": "Il reddito non si accumula - usalo o perdilo!",
        "vip_rules_8": "I pacchetti superiori danno +0.5% di reddito giornaliero rispetto al livello precedente",
        "current_status": "Stato attuale",
        "purchase_package": "Acquista un pacchetto per accedere a funzionalità premium",
        "available_for_withdrawal": "Disponibile per il prelievo",
        "today": "oggi",
        "claim_income": "RITIRA REDDITO",
        "no_available_income": "NESSUN REDDITO DISPONIBILE",
        "already_claimed": "GIÀ RITIRATO",
        "buy_vip_package": "Acquista un pacchetto VIP per guadagnare reddito",
        "next_claim": "Prossimo ritiro",
        "available_for": "Disponibile per",
        "analysis": "Analisi",
        "processing": "Elaborazione",
        "completion": "Completamento",
        "change_password": "Cambia password",
        "current_password": "Password attuale",
        "new_password": "Nuova password",
        "confirm_new_password": "Conferma nuova password",
        "update_password": "Aggiorna password",
        "identity_verification": "Verifica identità",
        "phone_number": "Numero di telefono",
        "not_verified": "Non verificato",
        "verified": "Verificato",
        "verify": "Verifica",
        "id_passport": "ID/Passaporto",
        "logout": "Disconnetti",
        "your_bonuses": "I tuoi bonus",
        "how_it_works": "Come funziona:",
        "referral_works_1": "8% dai depositi di 1a generazione",
        "referral_works_2": "3% dai depositi di 2a generazione",
        "referral_works_3": "1% dai depositi di 3a generazione",
        "referral_works_4": "Reddito accreditato istantaneamente quando i referral acquistano pacchetti VIP",
        "available_bonuses": "Bonus disponibili",
        "complete_tasks": "Completa attività e guadagna ricompense aggiuntive",
        "task": "Attività",
        "bonus": "Bonus",
        "status": "Stato",
        "registration_bonus_task": "Bonus di registrazione",
        "purchase_vip2": "Acquista Pacchetto VIP 2",
        "purchase_vip3": "Acquista Pacchetto VIP 3",
        "purchase_vip4": "Acquista Pacchetto VIP 4",
        "1st_gen_deposit_50": "Deposito 1a generazione 50 USDT",
        "1st_gen_deposit_100": "Deposito 1a generazione 100 USDT",
        "1st_gen_deposit_300": "Deposito 1a generazione 300 USDT",
        "1st_gen_deposit_1000": "Deposito 1a generazione 1000 USDT",
        "completed": "Completato",
        "available_task": "Disponibile",
        "terms_conditions": "Termini e condizioni:",
        "terms_1": "Tutti i bonus sono accreditati manualmente dall'amministrazione",
        "terms_2": "I bonus acquisto VIP vengono assegnati dopo l'attivazione riuscita del pacchetto",
        "terms_3": "I bonus deposito referral richiedono importi minimi di deposito dagli utenti di 1a generazione",
        "terms_4": "I bonus sono pagati in equivalente USDT",
        "terms_5": "L'amministrazione si riserva il diritto di modificare i termini dei bonus",
        "license_documents": "Licenza e documenti",
        "official_financial_license": "LICENZA FINANZIARIA UFFICIALE",
        "certificate_authorization": "Certificato di autorizzazione",
        "license_number": "Numero di licenza",
        "company_name": "Nome azienda",
        "registration_address": "Indirizzo di registrazione",
        "date_issue": "Data di emissione",
        "valid_until": "Valido fino al",
        "regulatory_body": "Organismo di regolamentazione",
        "authorized_signature": "Firma autorizzata",
        "director_licensing": "Direttore delle licenze",
        "official_seal": "Sigillo regolatorio ufficiale",
        "supporting_documents": "Documenti di supporto",
        "financial_report": "Relazione finanziaria 2024",
        "annual_audit": "Dichiarazione di audit annuale",
        "insurance_certificate": "Certificato di assicurazione",
        "client_fund_protection": "Protezione fondi clienti",
        "legal_information": "Informazioni legali",
        "verified_license": "LICENZA VERIFICATA • VALIDA FINO AL 2037",
        "copy": "Copia",
        "copied": "Copiato!",
        "logout_confirm": "Sei sicuro di volerti disconnettere?",
        "cancel": "Annulla",
        "confirm": "Conferma",
        "active": "ATTIVO",
        "buy": "ACQUISTA"
    }
};

// ... остальной код остается без изменений
let currentLanguage = 'en';

function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('preferredLanguage', lang);
    applyTranslations();
    updateLanguageSelector();
}

function applyTranslations() {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            if (element.tagName === 'INPUT' && element.type !== 'button' && element.type !== 'submit') {
                element.placeholder = translations[currentLanguage][key];
            } else {
                element.textContent = translations[currentLanguage][key];
            }
        }
    });
}

function updateLanguageSelector() {
    const selector = document.querySelector('.language-selector');
    if (selector) {
        const currentFlag = selector.querySelector('.current-flag');
        if (currentFlag) {
            currentFlag.textContent = getFlagEmoji(currentLanguage);
        }
    }
}

function getFlagEmoji(lang) {
    const flagEmojis = {
        'en': '🇺🇸',
        'es': '🇪🇸', 
        'de': '🇩🇪',
        'pl': '🇵🇱',
        'ru': '🇷🇺',
        'tr': '🇹🇷',
        'ar': '🇸🇦',
        'ro': '🇷🇴',
        'uk': '🇺🇦',
        'fr': '🇫🇷',
        'it': '🇮🇹'
    };
    return flagEmojis[lang] || '🌐';
}

function toggleLanguageMenu() {
    const menu = document.getElementById('languageMenu');
    if (menu) {
        menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
    }
}

function closeLanguageMenu() {
    const menu = document.getElementById('languageMenu');
    if (menu) {
        menu.style.display = 'none';
    }
}

// Initialize language on page load
document.addEventListener('DOMContentLoaded', function() {
    const savedLanguage = localStorage.getItem('preferredLanguage') || 'en';
    setLanguage(savedLanguage);
    
    // Close language menu when clicking outside
    document.addEventListener('click', function(event) {
        const selector = document.querySelector('.language-selector');
        if (selector && !selector.contains(event.target)) {
            closeLanguageMenu();
        }
    });
});
