// translate.js
const translations = {
    en: {
        // Login Page
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "email": "Email",
        "password": "Password",
        "confirm_password": "Confirm Password",
        "payment_password": "Payment Password",
        "referral_code": "Referral Code (optional)",
        "enter_username": "Enter username",
        "enter_email": "Enter email",
        "enter_password": "Enter password",
        "confirm_password_placeholder": "Confirm password",
        "enter_payment_password": "Enter payment password",
        "enter_referral_code": "Enter referral code",
        "invalid_credentials": "Invalid login credentials",
        "registration_bonus": "Congratulations! You received 3.00 USDT registration bonus!",
        
        // Dashboard
        "deposit": "Deposit",
        "withdraw": "Withdraw",
        "team": "Team",
        "task_center": "Task Center",
        "invite_friends": "Invite Friends",
        "history": "History",
        "download": "Download",
        "license": "License",
        "total_balance": "Total Balance",
        "from_referrals": "From Referrals",
        "from_bonuses": "From Bonuses",
        "from_quantification": "From Quantification",
        "available": "Available",
        "transaction_history": "Transaction History",
        "all": "All",
        "deposits": "Deposits",
        "withdrawals": "Withdrawals",
        "referrals": "Referrals",
        "quantification": "Quantification",
        "1st_generation": "1st Generation",
        "2nd_generation": "2nd Generation",
        "3rd_generation": "3rd Generation",
        "from_1st_generation": "8% from 1st Generation",
        "from_2nd_generation": "3% from 2nd Generation",
        "from_3rd_generation": "1% from 3rd Generation",
        "vip_packages": "VIP Packages",
        "current_status": "Current Status",
        "purchase_package": "Purchase a package to access premium features",
        "available_for_withdrawal": "Available for withdrawal",
        "today": "today",
        "claim_income": "CLAIM INCOME",
        "no_available_income": "NO AVAILABLE INCOME",
        "buy_vip_earn": "Buy a VIP package to earn income",
        "analysis": "Analysis",
        "processing": "Processing",
        "completion": "Completion",
        "profile": "Profile",
        "change_password": "Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "update_password": "Update Password",
        "identity_verification": "Identity Verification",
        "phone_number": "Phone Number",
        "id_passport": "ID/Passport",
        "not_verified": "Not verified",
        "verified": "Verified",
        "verify": "Verify",
        "logout": "Logout",
        "your_bonuses": "Your Bonuses",
        "available_bonuses": "Available Bonuses",
        "complete_tasks": "Complete tasks and earn additional rewards",
        "task": "Task",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registration Bonus",
        "terms_conditions": "Terms & Conditions",
        "license_documents": "License & Documents",
        "official_financial_license": "OFFICIAL FINANCIAL LICENSE",
        "certificate_authorization": "Certificate of Authorization",
        "license_number": "License Number",
        "company_name": "Company Name",
        "registration_address": "Registration Address",
        "date_issue": "Date of Issue",
        "valid_until": "Valid Until",
        "regulatory_body": "Regulatory Body",
        "authorized_signature": "Authorized Signature",
        "official_seal": "Official Regulatory Seal",
        "supporting_documents": "Supporting Documents",
        "financial_report": "Financial Report 2024",
        "annual_audit": "Annual Audit Statement",
        "insurance_certificate": "Insurance Certificate",
        "client_fund_protection": "Client Fund Protection",
        "legal_information": "Legal Information",
        "verified_license": "VERIFIED LICENSE • VALID UNTIL 2037",
        "loading": "Loading...",
        "copied": "Copied!",
        "copy_failed": "Failed to copy to clipboard",
        "phone_verified": "Phone number verified successfully!",
        "id_verified": "ID/Passport verified successfully!",
        "password_updated": "Password updated successfully!",
        "logout_confirm": "Are you sure you want to logout?",
        "vip_purchased": "VIP {level} package purchased successfully!",
        "insufficient_balance": "Insufficient balance to purchase this VIP package",
        "package_already_active": "VIP {level} package is already active!",
        "income_claimed": "Successfully claimed {amount} USDT daily income!",
        "cannot_claim": "You cannot claim income at this time. Please check the timer.",
        "no_income": "No available income to claim. Purchase a VIP package to start earning.",
        "already_claimed": "You have already claimed your daily income. Come back tomorrow at 22:00 UTC."
    },
    es: {
        // Spanish translations
        "login": "Iniciar Sesión",
        "register": "Registrarse",
        "username": "Usuario",
        "email": "Correo Electrónico",
        "password": "Contraseña",
        "confirm_password": "Confirmar Contraseña",
        "payment_password": "Contraseña de Pago",
        "referral_code": "Código de Referencia (opcional)",
        "enter_username": "Ingrese usuario",
        "enter_email": "Ingrese correo electrónico",
        "enter_password": "Ingrese contraseña",
        "confirm_password_placeholder": "Confirmar contraseña",
        "enter_payment_password": "Ingrese contraseña de pago",
        "enter_referral_code": "Ingrese código de referencia",
        "invalid_credentials": "Credenciales de inicio de sesión inválidas",
        "registration_bonus": "¡Felicitaciones! Recibiste 3.00 USDT de bono de registro!",
        "deposit": "Depositar",
        "withdraw": "Retirar",
        "team": "Equipo",
        "task_center": "Centro de Tareas",
        "invite_friends": "Invitar Amigos",
        "history": "Historial",
        "download": "Descargar",
        "license": "Licencia",
        "total_balance": "Saldo Total",
        "from_referrals": "De Referidos",
        "from_bonuses": "De Bonos",
        "from_quantification": "De Cuantificación",
        "available": "Disponible",
        "transaction_history": "Historial de Transacciones",
        "all": "Todo",
        "deposits": "Depósitos",
        "withdrawals": "Retiros",
        "referrals": "Referidos",
        "quantification": "Cuantificación",
        "1st_generation": "1ra Generación",
        "2nd_generation": "2da Generación",
        "3rd_generation": "3ra Generación",
        "from_1st_generation": "8% de 1ra Generación",
        "from_2nd_generation": "3% de 2da Generación",
        "from_3rd_generation": "1% de 3ra Generación",
        "vip_packages": "Paquetes VIP",
        "current_status": "Estado Actual",
        "purchase_package": "Compra un paquete para acceder a funciones premium",
        "available_for_withdrawal": "Disponible para retiro",
        "today": "hoy",
        "claim_income": "RECLAMAR INGRESO",
        "no_available_income": "SIN INGRESO DISPONIBLE",
        "buy_vip_earn": "Compra un paquete VIP para ganar ingresos",
        "analysis": "Análisis",
        "processing": "Procesando",
        "completion": "Finalización",
        "profile": "Perfil",
        "change_password": "Cambiar Contraseña",
        "current_password": "Contraseña Actual",
        "new_password": "Nueva Contraseña",
        "confirm_new_password": "Confirmar Nueva Contraseña",
        "update_password": "Actualizar Contraseña",
        "identity_verification": "Verificación de Identidad",
        "phone_number": "Número de Teléfono",
        "id_passport": "ID/Pasaporte",
        "not_verified": "No verificado",
        "verified": "Verificado",
        "verify": "Verificar",
        "logout": "Cerrar Sesión",
        "your_bonuses": "Tus Bonos",
        "available_bonuses": "Bonos Disponibles",
        "complete_tasks": "Completa tareas y gana recompensas adicionales",
        "task": "Tarea",
        "bonus": "Bono",
        "status": "Estado",
        "registration_bonus_task": "Bono de Registro",
        "terms_conditions": "Términos y Condiciones",
        "license_documents": "Licencia y Documentos",
        "official_financial_license": "LICENCIA FINANCIERA OFICIAL",
        "certificate_authorization": "Certificado de Autorización",
        "license_number": "Número de Licencia",
        "company_name": "Nombre de la Empresa",
        "registration_address": "Dirección de Registro",
        "date_issue": "Fecha de Emisión",
        "valid_until": "Válido Hasta",
        "regulatory_body": "Organismo Regulador",
        "authorized_signature": "Firma Autorizada",
        "official_seal": "Sello Oficial Regulatorio",
        "supporting_documents": "Documentos de Soporte",
        "financial_report": "Reporte Financiero 2024",
        "annual_audit": "Estado de Auditoría Anual",
        "insurance_certificate": "Certificado de Seguro",
        "client_fund_protection": "Protección de Fondos del Cliente",
        "legal_information": "Información Legal",
        "verified_license": "LICENCIA VERIFICADA • VÁLIDA HASTA 2037",
        "loading": "Cargando...",
        "copied": "¡Copiado!",
        "copy_failed": "Error al copiar al portapapeles",
        "phone_verified": "¡Número de teléfono verificado exitosamente!",
        "id_verified": "¡ID/Pasaporte verificado exitosamente!",
        "password_updated": "¡Contraseña actualizada exitosamente!",
        "logout_confirm": "¿Estás seguro de que quieres cerrar sesión?",
        "vip_purchased": "¡Paquete VIP {level} comprado exitosamente!",
        "insufficient_balance": "Saldo insuficiente para comprar este paquete VIP",
        "package_already_active": "¡El paquete VIP {level} ya está activo!",
        "income_claimed": "¡Ingreso diario de {amount} USDT reclamado exitosamente!",
        "cannot_claim": "No puedes reclamar ingresos en este momento. Por favor verifica el temporizador.",
        "no_income": "No hay ingresos disponibles para reclamar. Compra un paquete VIP para comenzar a ganar.",
        "already_claimed": "Ya reclamaste tu ingreso diario. Vuelve mañana a las 22:00 UTC."
    },
    de: {
        // German translations
        "login": "Anmelden",
        "register": "Registrieren",
        "username": "Benutzername",
        "email": "E-Mail",
        "password": "Passwort",
        "confirm_password": "Passwort bestätigen",
        "payment_password": "Zahlungspasswort",
        "referral_code": "Empfehlungscode (optional)",
        "enter_username": "Benutzername eingeben",
        "enter_email": "E-Mail eingeben",
        "enter_password": "Passwort eingeben",
        "confirm_password_placeholder": "Passwort bestätigen",
        "enter_payment_password": "Zahlungspasswort eingeben",
        "enter_referral_code": "Empfehlungscode eingeben",
        "invalid_credentials": "Ungültige Anmeldedaten",
        "registration_bonus": "Herzlichen Glückwunsch! Sie haben 3.00 USDT Registrierungsbonus erhalten!",
        "deposit": "Einzahlen",
        "withdraw": "Auszahlen",
        "team": "Team",
        "task_center": "Aufgabencenter",
        "invite_friends": "Freunde einladen",
        "history": "Verlauf",
        "download": "Herunterladen",
        "license": "Lizenz",
        "total_balance": "Gesamtguthaben",
        "from_referrals": "Von Empfehlungen",
        "from_bonuses": "Von Boni",
        "from_quantification": "Von Quantifizierung",
        "available": "Verfügbar",
        "transaction_history": "Transaktionsverlauf",
        "all": "Alle",
        "deposits": "Einzahlungen",
        "withdrawals": "Auszahlungen",
        "referrals": "Empfehlungen",
        "quantification": "Quantifizierung",
        "1st_generation": "1. Generation",
        "2nd_generation": "2. Generation",
        "3rd_generation": "3. Generation",
        "from_1st_generation": "8% von 1. Generation",
        "from_2nd_generation": "3% von 2. Generation",
        "from_3rd_generation": "1% von 3. Generation",
        "vip_packages": "VIP-Pakete",
        "current_status": "Aktueller Status",
        "purchase_package": "Kaufen Sie ein Paket, um auf Premium-Funktionen zuzugreifen",
        "available_for_withdrawal": "Verfügbar für Auszahlung",
        "today": "heute",
        "claim_income": "EINKOMMEN ABHOLEN",
        "no_available_income": "KEIN VERFÜGBARES EINKOMMEN",
        "buy_vip_earn": "Kaufen Sie ein VIP-Paket, um Einkommen zu verdienen",
        "analysis": "Analyse",
        "processing": "Verarbeitung",
        "completion": "Abschluss",
        "profile": "Profil",
        "change_password": "Passwort ändern",
        "current_password": "Aktuelles Passwort",
        "new_password": "Neues Passwort",
        "confirm_new_password": "Neues Passwort bestätigen",
        "update_password": "Passwort aktualisieren",
        "identity_verification": "Identitätsverifizierung",
        "phone_number": "Telefonnummer",
        "id_passport": "Ausweis/Reisepass",
        "not_verified": "Nicht verifiziert",
        "verified": "Verifiziert",
        "verify": "Verifizieren",
        "logout": "Abmelden",
        "your_bonuses": "Ihre Boni",
        "available_bonuses": "Verfügbare Boni",
        "complete_tasks": "Erledigen Sie Aufgaben und verdienen Sie zusätzliche Belohnungen",
        "task": "Aufgabe",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registrierungsbonus",
        "terms_conditions": "Geschäftsbedingungen",
        "license_documents": "Lizenz & Dokumente",
        "official_financial_license": "OFFIZIELLE FINANZLIZENZ",
        "certificate_authorization": "Berechtigungszertifikat",
        "license_number": "Lizenznummer",
        "company_name": "Firmenname",
        "registration_address": "Registrierungsadresse",
        "date_issue": "Ausstellungsdatum",
        "valid_until": "Gültig bis",
        "regulatory_body": "Regulierungsbehörde",
        "authorized_signature": "Autorisierte Unterschrift",
        "official_seal": "Offizielles Regulierungssiegel",
        "supporting_documents": "Unterstützende Dokumente",
        "financial_report": "Finanzbericht 2024",
        "annual_audit": "Jahresabschlussprüfung",
        "insurance_certificate": "Versicherungszertifikat",
        "client_fund_protection": "Kundengeldabsicherung",
        "legal_information": "Rechtliche Informationen",
        "verified_license": "VERIFIZIERTE LIZENZ • GÜLTIG BIS 2037",
        "loading": "Lädt...",
        "copied": "Kopiert!",
        "copy_failed": "Fehler beim Kopieren in die Zwischenablage",
        "phone_verified": "Telefonnummer erfolgreich verifiziert!",
        "id_verified": "Ausweis/Reisepass erfolgreich verifiziert!",
        "password_updated": "Passwort erfolgreich aktualisiert!",
        "logout_confirm": "Möchten Sie sich wirklich abmelden?",
        "vip_purchased": "VIP {level} Paket erfolgreich gekauft!",
        "insufficient_balance": "Unzureichendes Guthaben zum Kauf dieses VIP-Pakets",
        "package_already_active": "VIP {level} Paket ist bereits aktiv!",
        "income_claimed": "Tägliches Einkommen von {amount} USDT erfolgreich abgeholt!",
        "cannot_claim": "Sie können derzeit kein Einkommen abholen. Bitte überprüfen Sie den Timer.",
        "no_income": "Kein verfügbares Einkommen zum Abholen. Kaufen Sie ein VIP-Paket, um mit dem Verdienen zu beginnen.",
        "already_claimed": "Sie haben Ihr tägliches Einkommen bereits abgeholt. Kommen Sie morgen um 22:00 UTC zurück."
    },
    // Add other languages similarly...
    ru: {
        // Russian translations
        "login": "Войти",
        "register": "Регистрация",
        "username": "Имя пользователя",
        "email": "Электронная почта",
        "password": "Пароль",
        "confirm_password": "Подтвердите пароль",
        "payment_password": "Платежный пароль",
        "referral_code": "Реферальный код (необязательно)",
        "enter_username": "Введите имя пользователя",
        "enter_email": "Введите электронную почту",
        "enter_password": "Введите пароль",
        "confirm_password_placeholder": "Подтвердите пароль",
        "enter_payment_password": "Введите платежный пароль",
        "enter_referral_code": "Введите реферальный код",
        "invalid_credentials": "Неверные учетные данные для входа",
        "registration_bonus": "Поздравляем! Вы получили 3.00 USDT бонус за регистрацию!",
        "deposit": "Пополнить",
        "withdraw": "Вывести",
        "team": "Команда",
        "task_center": "Центр заданий",
        "invite_friends": "Пригласить друзей",
        "history": "История",
        "download": "Скачать",
        "license": "Лицензия",
        "total_balance": "Общий баланс",
        "from_referrals": "От рефералов",
        "from_bonuses": "От бонусов",
        "from_quantification": "От квантификации",
        "available": "Доступно",
        "transaction_history": "История транзакций",
        "all": "Все",
        "deposits": "Пополнения",
        "withdrawals": "Выводы",
        "referrals": "Рефералы",
        "quantification": "Квантификация",
        "1st_generation": "1-е поколение",
        "2nd_generation": "2-е поколение",
        "3rd_generation": "3-е поколение",
        "from_1st_generation": "8% от 1-го поколения",
        "from_2nd_generation": "3% от 2-го поколения",
        "from_3rd_generation": "1% от 3-го поколения",
        "vip_packages": "VIP пакеты",
        "current_status": "Текущий статус",
        "purchase_package": "Приобретите пакет для доступа к премиум-функциям",
        "available_for_withdrawal": "Доступно для вывода",
        "today": "сегодня",
        "claim_income": "ПОЛУЧИТЬ ДОХОД",
        "no_available_income": "ДОХОД НЕДОСТУПЕН",
        "buy_vip_earn": "Купите VIP пакет, чтобы начать зарабатывать",
        "analysis": "Анализ",
        "processing": "Обработка",
        "completion": "Завершение",
        "profile": "Профиль",
        "change_password": "Изменить пароль",
        "current_password": "Текущий пароль",
        "new_password": "Новый пароль",
        "confirm_new_password": "Подтвердите новый пароль",
        "update_password": "Обновить пароль",
        "identity_verification": "Верификация личности",
        "phone_number": "Номер телефона",
        "id_passport": "ID/Паспорт",
        "not_verified": "Не верифицировано",
        "verified": "Верифицировано",
        "verify": "Верифицировать",
        "logout": "Выйти",
        "your_bonuses": "Ваши бонусы",
        "available_bonuses": "Доступные бонусы",
        "complete_tasks": "Выполняйте задания и получайте дополнительные награды",
        "task": "Задание",
        "bonus": "Бонус",
        "status": "Статус",
        "registration_bonus_task": "Бонус за регистрацию",
        "terms_conditions": "Условия и положения",
        "license_documents": "Лицензия и документы",
        "official_financial_license": "ОФИЦИАЛЬНАЯ ФИНАНСОВАЯ ЛИЦЕНЗИЯ",
        "certificate_authorization": "Сертификат авторизации",
        "license_number": "Номер лицензии",
        "company_name": "Название компании",
        "registration_address": "Адрес регистрации",
        "date_issue": "Дата выдачи",
        "valid_until": "Действительно до",
        "regulatory_body": "Регулирующий орган",
        "authorized_signature": "Авторизованная подпись",
        "official_seal": "Официальная печать регулятора",
        "supporting_documents": "Поддерживающие документы",
        "financial_report": "Финансовый отчет 2024",
        "annual_audit": "Годовой аудиторский отчет",
        "insurance_certificate": "Страховой сертификат",
        "client_fund_protection": "Защита клиентских средств",
        "legal_information": "Юридическая информация",
        "verified_license": "ПРОВЕРЕННАЯ ЛИЦЕНЗИЯ • ДЕЙСТВИТЕЛЬНА ДО 2037",
        "loading": "Загрузка...",
        "copied": "Скопировано!",
        "copy_failed": "Не удалось скопировать в буфер обмена",
        "phone_verified": "Номер телефона успешно верифицирован!",
        "id_verified": "ID/Паспорт успешно верифицирован!",
        "password_updated": "Пароль успешно обновлен!",
        "logout_confirm": "Вы уверены, что хотите выйти?",
        "vip_purchased": "VIP пакет {level} успешно приобретен!",
        "insufficient_balance": "Недостаточно средств для покупки этого VIP пакета",
        "package_already_active": "VIP пакет {level} уже активен!",
        "income_claimed": "Ежедневный доход {amount} USDT успешно получен!",
        "cannot_claim": "Вы не можете получить доход в это время. Пожалуйста, проверьте таймер.",
        "no_income": "Нет доступного дохода для получения. Приобретите VIP пакет, чтобы начать зарабатывать.",
        "already_claimed": "Вы уже получили свой ежедневный доход. Возвращайтесь завтра в 22:00 UTC."
    }
    // Add other languages: pl, tr, ar, ro, uk, fr, it with similar structure
};

let currentLanguage = 'en';

function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('preferredLanguage', lang);
    applyTranslations();
}

function applyTranslations() {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[currentLanguage][key];
            } else {
                element.textContent = translations[currentLanguage][key];
            }
        }
    });
}

function getTranslation(key, params = {}) {
    let text = translations[currentLanguage] && translations[currentLanguage][key] 
        ? translations[currentLanguage][key] 
        : translations['en'][key] || key;
    
    // Replace parameters
    Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
}

// Initialize language on load
document.addEventListener('DOMContentLoaded', function() {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && translations[savedLanguage]) {
        currentLanguage = savedLanguage;
    }
    applyTranslations();
});
