// translate.js
const translations = {
    en: {
        // Login Page
        "login": "Login",
        "register": "Register",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "confirm_password": "Confirm Password",
        "payment_password": "Payment Password",
        "referral_code": "Referral Code (optional)",
        "enter_username": "Enter username",
        "enter_password": "Enter password",
        "enter_email": "Enter email",
        "enter_payment_password": "Enter payment password",
        "enter_referral_code": "Enter referral code",
        "invalid_credentials": "Invalid login credentials",
        "registration_bonus": "Congratulations! You received 3.00 USDT registration bonus!",
        
        // Dashboard
        "home": "Home",
        "vip": "VIP",
        "assets": "Assets",
        "profile": "Profile",
        "deposit": "Deposit",
        "withdraw": "Withdraw",
        "team": "Team",
        "task_center": "Task Center",
        "invite_friends": "Invite Friends",
        "history": "History",
        "download": "Download",
        "license": "License",
        "total_balance": "Total Balance",
        "from_referrals": "From Referrals",
        "from_bonuses": "From Bonuses",
        "from_quantification": "From Quantification",
        "available": "Available",
        "transaction_history": "Transaction History",
        "all": "All",
        "deposits": "Deposits",
        "withdrawals": "Withdrawals",
        "referrals": "Referrals",
        "quantification": "Quantification",
        "no_transactions": "No transactions found",
        "loading_transactions": "Loading transactions...",
        "1st_generation": "1st Generation",
        "2nd_generation": "2nd Generation",
        "3rd_generation": "3rd Generation",
        "loading_referrals": "Loading referrals...",
        "no_referrals": "No referrals yet. Share your referral link to invite friends!",
        "vip_packages": "VIP Packages",
        "vip_rules": "VIP Package Rules:",
        "vip_rule_1": "VIP packages are active for exactly 30 days",
        "vip_rule_2": "Daily income: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rule_3": "Package price is returned to your balance after 30 days automatically",
        "vip_rule_4": "Package expires after 30 days - to continue earning, purchase again",
        "vip_rule_5": "You can claim daily income once per day at 22:00 UTC",
        "vip_rule_6": "If you don't claim income today, you can claim it until 22:00 UTC tomorrow",
        "vip_rule_7": "Income doesn't accumulate - use it or lose it!",
        "vip_rule_8": "Higher packages give +0.5% daily income compared to previous level",
        "quantification_title": "Quantification",
        "current_status": "Current Status",
        "purchase_package": "Purchase a package to access premium features",
        "available_withdrawal": "Available for withdrawal",
        "today": "today",
        "claim_income": "CLAIM INCOME",
        "no_available_income": "NO AVAILABLE INCOME",
        "already_claimed": "ALREADY CLAIMED",
        "buy_vip_earn": "Buy a VIP package to earn income",
        "next_claim": "Next claim",
        "available_for": "Available for",
        "analysis": "Analysis",
        "processing": "Processing",
        "completion": "Completion",
        "change_password": "Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "update_password": "Update Password",
        "identity_verification": "Identity Verification",
        "phone_number": "Phone Number",
        "id_passport": "ID/Passport",
        "not_verified": "Not verified",
        "verified": "Verified",
        "verify": "Verify",
        "logout": "Logout",
        "logout_confirm": "Are you sure you want to logout?",
        "your_bonuses": "Your Bonuses",
        "how_it_works": "How it works:",
        "referral_works_1": "8% from 1st generation deposits",
        "referral_works_2": "3% from 2nd generation deposits",
        "referral_works_3": "1% from 3rd generation deposits",
        "referral_works_4": "Income credited instantly when referrals purchase VIP packages",
        "available_bonuses": "Available Bonuses",
        "complete_tasks": "Complete tasks and earn additional rewards",
        "task": "Task",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registration Bonus",
        "terms_conditions": "Terms & Conditions:",
        "terms_1": "All bonuses are credited manually by administration",
        "terms_2": "VIP purchase bonuses are awarded after successful package activation",
        "terms_3": "Referral deposit bonuses require minimum deposit amounts from 1st generation users",
        "terms_4": "Bonuses are paid in USDT equivalent",
        "terms_5": "Administration reserves the right to modify bonus terms",
        "license_documents": "License & Documents",
        "official_financial_license": "OFFICIAL FINANCIAL LICENSE",
        "certificate_authorization": "Certificate of Authorization",
        "license_number": "License Number",
        "company_name": "Company Name",
        "registration_address": "Registration Address",
        "date_issue": "Date of Issue",
        "valid_until": "Valid Until",
        "regulatory_body": "Regulatory Body",
        "authorized_signature": "Authorized Signature",
        "director_licensing": "Director of Licensing",
        "official_seal": "Official Regulatory Seal",
        "supporting_documents": "Supporting Documents",
        "financial_report": "Financial Report 2024",
        "annual_audit": "Annual Audit Statement",
        "insurance_certificate": "Insurance Certificate",
        "client_fund_protection": "Client Fund Protection",
        "legal_information": "Legal Information",
        "verified_license": "VERIFIED LICENSE • VALID UNTIL 2037",
        "loading": "Loading...",
        "copied": "Copied!",
        "copy_failed": "Failed to copy to clipboard",
        "purchase_success": "VIP {level} package purchased successfully!",
        "insufficient_balance": "Insufficient balance to purchase this VIP package",
        "package_active": "VIP {level} package is already active!",
        "purchase_failed": "Purchase failed. Please try again.",
        "income_claimed": "Successfully claimed {amount} USDT daily income!",
        "claim_failed": "Failed to claim income. Please try again.",
        "password_updated": "Password updated successfully!",
        "password_incorrect": "Current password is incorrect",
        "password_mismatch": "New password and confirmation do not match",
        "password_short": "New password must be at least 6 characters long",
        "fill_all_fields": "Please fill in all password fields",
        "phone_verified": "Phone number verified successfully!",
        "id_verified": "ID/Passport verified successfully!",
        "data_error": "Error loading data. Please refresh the page.",
        "claim_not_available": "You cannot claim income at this time. Please check the timer.",
        "no_income": "No available income to claim. Purchase a VIP package to start earning.",
        "already_claimed_today": "You have already claimed your daily income. Come back tomorrow at 22:00 UTC."
    },
    es: {
        "login": "Iniciar Sesión",
        "register": "Registrarse",
        "username": "Nombre de Usuario",
        "password": "Contraseña",
        "email": "Correo Electrónico",
        "confirm_password": "Confirmar Contraseña",
        "payment_password": "Contraseña de Pago",
        "referral_code": "Código de Referencia (opcional)",
        "enter_username": "Ingrese nombre de usuario",
        "enter_password": "Ingrese contraseña",
        "enter_email": "Ingrese correo electrónico",
        "enter_payment_password": "Ingrese contraseña de pago",
        "enter_referral_code": "Ingrese código de referencia",
        "invalid_credentials": "Credenciales de inicio de sesión inválidas",
        "registration_bonus": "¡Felicidades! ¡Recibiste 3.00 USDT de bono de registro!",
        "home": "Inicio",
        "vip": "VIP",
        "assets": "Activos",
        "profile": "Perfil",
        "deposit": "Depositar",
        "withdraw": "Retirar",
        "team": "Equipo",
        "task_center": "Centro de Tareas",
        "invite_friends": "Invitar Amigos",
        "history": "Historial",
        "download": "Descargar",
        "license": "Licencia",
        "total_balance": "Saldo Total",
        "from_referrals": "De Referidos",
        "from_bonuses": "De Bonos",
        "from_quantification": "De Cuantificación",
        "available": "Disponible",
        "transaction_history": "Historial de Transacciones",
        "all": "Todo",
        "deposits": "Depósitos",
        "withdrawals": "Retiros",
        "referrals": "Referidos",
        "quantification": "Cuantificación",
        "no_transactions": "No se encontraron transacciones",
        "loading_transactions": "Cargando transacciones...",
        "1st_generation": "1ra Generación",
        "2nd_generation": "2da Generación",
        "3rd_generation": "3ra Generación",
        "loading_referrals": "Cargando referidos...",
        "no_referrals": "Aún no hay referidos. ¡Comparte tu enlace de referencia para invitar amigos!",
        "vip_packages": "Paquetes VIP",
        "vip_rules": "Reglas de Paquetes VIP:",
        "vip_rule_1": "Los paquetes VIP están activos exactamente 30 días",
        "vip_rule_2": "Ingreso diario: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rule_3": "El precio del paquete se devuelve a tu saldo después de 30 días automáticamente",
        "vip_rule_4": "El paquete expira después de 30 días - para continuar ganando, compra nuevamente",
        "vip_rule_5": "Puedes reclamar ingresos diarios una vez al día a las 22:00 UTC",
        "vip_rule_6": "Si no reclamas ingresos hoy, puedes reclamarlos hasta las 22:00 UTC de mañana",
        "vip_rule_7": "Los ingresos no se acumulan - ¡úsalos o piérdelos!",
        "vip_rule_8": "Los paquetes superiores dan +0.5% de ingreso diario comparado con el nivel anterior",
        "quantification_title": "Cuantificación",
        "current_status": "Estado Actual",
        "purchase_package": "Compra un paquete para acceder a funciones premium",
        "available_withdrawal": "Disponible para retiro",
        "today": "hoy",
        "claim_income": "RECLAMAR INGRESO",
        "no_available_income": "SIN INGRESO DISPONIBLE",
        "already_claimed": "YA RECLAMADO",
        "buy_vip_earn": "Compra un paquete VIP para ganar ingresos",
        "next_claim": "Próximo reclamo",
        "available_for": "Disponible por",
        "analysis": "Análisis",
        "processing": "Procesando",
        "completion": "Finalización",
        "change_password": "Cambiar Contraseña",
        "current_password": "Contraseña Actual",
        "new_password": "Nueva Contraseña",
        "confirm_new_password": "Confirmar Nueva Contraseña",
        "update_password": "Actualizar Contraseña",
        "identity_verification": "Verificación de Identidad",
        "phone_number": "Número de Teléfono",
        "id_passport": "ID/Pasaporte",
        "not_verified": "No verificado",
        "verified": "Verificado",
        "verify": "Verificar",
        "logout": "Cerrar Sesión",
        "logout_confirm": "¿Estás seguro de que quieres cerrar sesión?",
        "your_bonuses": "Tus Bonos",
        "how_it_works": "Cómo funciona:",
        "referral_works_1": "8% de depósitos de 1ra generación",
        "referral_works_2": "3% de depósitos de 2da generación",
        "referral_works_3": "1% de depósitos de 3ra generación",
        "referral_works_4": "Ingreso acreditado instantáneamente cuando los referidos compran paquetes VIP",
        "available_bonuses": "Bonos Disponibles",
        "complete_tasks": "Completa tareas y gana recompensas adicionales",
        "task": "Tarea",
        "bonus": "Bono",
        "status": "Estado",
        "registration_bonus_task": "Bono de Registro",
        "terms_conditions": "Términos y Condiciones:",
        "terms_1": "Todos los bonos son acreditados manualmente por la administración",
        "terms_2": "Los bonos de compra VIP se otorgan después de la activación exitosa del paquete",
        "terms_3": "Los bonos de depósito de referidos requieren montos mínimos de depósito de usuarios de 1ra generación",
        "terms_4": "Los bonos se pagan en equivalente USDT",
        "terms_5": "La administración se reserva el derecho de modificar los términos de los bonos",
        "license_documents": "Licencia y Documentos",
        "official_financial_license": "LICENCIA FINANCIERA OFICIAL",
        "certificate_authorization": "Certificado de Autorización",
        "license_number": "Número de Licencia",
        "company_name": "Nombre de la Empresa",
        "registration_address": "Dirección de Registro",
        "date_issue": "Fecha de Emisión",
        "valid_until": "Válido Hasta",
        "regulatory_body": "Organismo Regulador",
        "authorized_signature": "Firma Autorizada",
        "director_licensing": "Director de Licencias",
        "official_seal": "Sello Regulatorio Oficial",
        "supporting_documents": "Documentos de Soporte",
        "financial_report": "Reporte Financiero 2024",
        "annual_audit": "Estado de Auditoría Anual",
        "insurance_certificate": "Certificado de Seguro",
        "client_fund_protection": "Protección de Fondos del Cliente",
        "legal_information": "Información Legal",
        "verified_license": "LICENCIA VERIFICADA • VÁLIDA HASTA 2037",
        "loading": "Cargando...",
        "copied": "¡Copiado!",
        "copy_failed": "Error al copiar al portapapeles",
        "purchase_success": "¡Paquete VIP {level} comprado exitosamente!",
        "insufficient_balance": "Saldo insuficiente para comprar este paquete VIP",
        "package_active": "¡El paquete VIP {level} ya está activo!",
        "purchase_failed": "Error en la compra. Por favor, intente nuevamente.",
        "income_claimed": "¡Ingreso diario de {amount} USDT reclamado exitosamente!",
        "claim_failed": "Error al reclamar ingresos. Por favor, intente nuevamente.",
        "password_updated": "¡Contraseña actualizada exitosamente!",
        "password_incorrect": "Contraseña actual incorrecta",
        "password_mismatch": "La nueva contraseña y la confirmación no coinciden",
        "password_short": "La nueva contraseña debe tener al menos 6 caracteres",
        "fill_all_fields": "Por favor, complete todos los campos de contraseña",
        "phone_verified": "¡Número de teléfono verificado exitosamente!",
        "id_verified": "¡ID/Pasaporte verificado exitosamente!",
        "data_error": "Error al cargar datos. Por favor, actualice la página.",
        "claim_not_available": "No puedes reclamar ingresos en este momento. Por favor, verifica el temporizador.",
        "no_income": "No hay ingresos disponibles para reclamar. Compra un paquete VIP para comenzar a ganar.",
        "already_claimed_today": "Ya has reclamado tus ingresos diarios. Vuelve mañana a las 22:00 UTC."
    },
    de: {
        "login": "Anmelden",
        "register": "Registrieren",
        "username": "Benutzername",
        "password": "Passwort",
        "email": "E-Mail",
        "confirm_password": "Passwort bestätigen",
        "payment_password": "Zahlungspasswort",
        "referral_code": "Empfehlungscode (optional)",
        "enter_username": "Benutzername eingeben",
        "enter_password": "Passwort eingeben",
        "enter_email": "E-Mail eingeben",
        "enter_payment_password": "Zahlungspasswort eingeben",
        "enter_referral_code": "Empfehlungscode eingeben",
        "invalid_credentials": "Ungültige Anmeldedaten",
        "registration_bonus": "Herzlichen Glückwunsch! Sie haben 3.00 USDT Registrierungsbonus erhalten!",
        "home": "Startseite",
        "vip": "VIP",
        "assets": "Vermögen",
        "profile": "Profil",
        "deposit": "Einzahlung",
        "withdraw": "Auszahlung",
        "team": "Team",
        "task_center": "Aufgabencenter",
        "invite_friends": "Freunde einladen",
        "history": "Verlauf",
        "download": "Download",
        "license": "Lizenz",
        "total_balance": "Gesamtguthaben",
        "from_referrals": "Von Empfehlungen",
        "from_bonuses": "Von Boni",
        "from_quantification": "Von Quantifizierung",
        "available": "Verfügbar",
        "transaction_history": "Transaktionsverlauf",
        "all": "Alle",
        "deposits": "Einzahlungen",
        "withdrawals": "Auszahlungen",
        "referrals": "Empfehlungen",
        "quantification": "Quantifizierung",
        "no_transactions": "Keine Transaktionen gefunden",
        "loading_transactions": "Lade Transaktionen...",
        "1st_generation": "1. Generation",
        "2nd_generation": "2. Generation",
        "3rd_generation": "3. Generation",
        "loading_referrals": "Lade Empfehlungen...",
        "no_referrals": "Noch keine Empfehlungen. Teile deinen Empfehlungslink, um Freunde einzuladen!",
        "vip_packages": "VIP-Pakete",
        "vip_rules": "VIP-Paket-Regeln:",
        "vip_rule_1": "VIP-Pakete sind genau 30 Tage aktiv",
        "vip_rule_2": "Tägliches Einkommen: VIP1: 2.6% (0.52 USDT) | VIP2: 3.1% (3.10 USDT) | VIP3: 3.6% (10.80 USDT) | VIP4: 4.1% (41.00 USDT) | VIP5: 4.6% (138.00 USDT) | VIP6: 5.1% (255.00 USDT)",
        "vip_rule_3": "Der Paketpreis wird nach 30 Tagen automatisch auf Ihr Guthaben zurückerstattet",
        "vip_rule_4": "Das Paket läuft nach 30 Tagen ab - um weiter zu verdienen, kaufen Sie erneut",
        "vip_rule_5": "Sie können tägliches Einkommen einmal pro Tag um 22:00 UTC abholen",
        "vip_rule_6": "Wenn Sie das Einkommen heute nicht abholen, können Sie es bis morgen 22:00 UTC abholen",
        "vip_rule_7": "Einkommen sammelt sich nicht an - nutzen Sie es oder verlieren Sie es!",
        "vip_rule_8": "Höhere Pakete geben +0.5% tägliches Einkommen im Vergleich zur vorherigen Stufe",
        "quantification_title": "Quantifizierung",
        "current_status": "Aktueller Status",
        "purchase_package": "Kaufen Sie ein Paket, um auf Premium-Funktionen zuzugreifen",
        "available_withdrawal": "Verfügbar für Auszahlung",
        "today": "heute",
        "claim_income": "EINKOMMEN ABHOLEN",
        "no_available_income": "KEIN VERFÜGBARES EINKOMMEN",
        "already_claimed": "BEREITS ABGEHOLT",
        "buy_vip_earn": "Kaufen Sie ein VIP-Paket, um Einkommen zu verdienen",
        "next_claim": "Nächste Abholung",
        "available_for": "Verfügbar für",
        "analysis": "Analyse",
        "processing": "Verarbeitung",
        "completion": "Abschluss",
        "change_password": "Passwort ändern",
        "current_password": "Aktuelles Passwort",
        "new_password": "Neues Passwort",
        "confirm_new_password": "Neues Passwort bestätigen",
        "update_password": "Passwort aktualisieren",
        "identity_verification": "Identitätsverifizierung",
        "phone_number": "Telefonnummer",
        "id_passport": "Ausweis/Reisepass",
        "not_verified": "Nicht verifiziert",
        "verified": "Verifiziert",
        "verify": "Verifizieren",
        "logout": "Abmelden",
        "logout_confirm": "Sind Sie sicher, dass Sie sich abmelden möchten?",
        "your_bonuses": "Ihre Boni",
        "how_it_works": "So funktioniert es:",
        "referral_works_1": "8% von Einzahlungen der 1. Generation",
        "referral_works_2": "3% von Einzahlungen der 2. Generation",
        "referral_works_3": "1% von Einzahlungen der 3. Generation",
        "referral_works_4": "Einkommen sofort gutgeschrieben, wenn Empfehlungen VIP-Pakete kaufen",
        "available_bonuses": "Verfügbare Boni",
        "complete_tasks": "Schließe Aufgaben ab und verdiene zusätzliche Belohnungen",
        "task": "Aufgabe",
        "bonus": "Bonus",
        "status": "Status",
        "registration_bonus_task": "Registrierungsbonus",
        "terms_conditions": "Geschäftsbedingungen:",
        "terms_1": "Alle Boni werden manuell von der Administration gutgeschrieben",
        "terms_2": "VIP-Kaufboni werden nach erfolgreicher Paketaktivierung vergeben",
        "terms_3": "Empfehlungseinzahlungsboni erfordern Mindesteinzahlungsbeträge von Nutzern der 1. Generation",
        "terms_4": "Boni werden in USDT-Äquivalent ausgezahlt",
        "terms_5": "Die Administration behält sich das Recht vor, die Bonusbedingungen zu ändern",
        "license_documents": "Lizenz & Dokumente",
        "official_financial_license": "OFFIZIELLE FINANZLIZENZ",
        "certificate_authorization": "Berechtigungszertifikat",
        "license_number": "Lizenznummer",
        "company_name": "Firmenname",
        "registration_address": "Registrierungsadresse",
        "date_issue": "Ausstellungsdatum",
        "valid_until": "Gültig bis",
        "regulatory_body": "Regulierungsbehörde",
        "authorized_signature": "Autorisierte Unterschrift",
        "director_licensing": "Lizenzierungsdirektor",
        "official_seal": "Offizielles Regulierungssiegel",
        "supporting_documents": "Unterstützende Dokumente",
        "financial_report": "Finanzbericht 2024",
        "annual_audit": "Jahresabschlussprüfung",
        "insurance_certificate": "Versicherungszertifikat",
        "client_fund_protection": "Kundengeldabsicherung",
        "legal_information": "Rechtliche Informationen",
        "verified_license": "VERIFIZIERTE LIZENZ • GÜLTIG BIS 2037",
        "loading": "Lädt...",
        "copied": "Kopiert!",
        "copy_failed": "Fehler beim Kopieren in die Zwischenablage",
        "purchase_success": "VIP {level} Paket erfolgreich gekauft!",
        "insufficient_balance": "Unzureichendes Guthaben zum Kauf dieses VIP-Pakets",
        "package_active": "VIP {level} Paket ist bereits aktiv!",
        "purchase_failed": "Kauf fehlgeschlagen. Bitte versuchen Sie es erneut.",
        "income_claimed": "Erfolgreich {amount} USDT Tageseinkommen abgeholt!",
        "claim_failed": "Fehler beim Abholen des Einkommens. Bitte versuchen Sie es erneut.",
        "password_updated": "Passwort erfolgreich aktualisiert!",
        "password_incorrect": "Aktuelles Passwort ist falsch",
        "password_mismatch": "Neues Passwort und Bestätigung stimmen nicht überein",
        "password_short": "Neues Passwort muss mindestens 6 Zeichen lang sein",
        "fill_all_fields": "Bitte füllen Sie alle Passwortfelder aus",
        "phone_verified": "Telefonnummer erfolgreich verifiziert!",
        "id_verified": "Ausweis/Reisepass erfolgreich verifiziert!",
        "data_error": "Fehler beim Laden der Daten. Bitte aktualisieren Sie die Seite.",
        "claim_not_available": "Sie können zu diesem Zeitpunkt kein Einkommen abholen. Bitte überprüfen Sie den Timer.",
        "no_income": "Kein verfügbares Einkommen zum Abholen. Kaufen Sie ein VIP-Paket, um mit dem Verdienen zu beginnen.",
        "already_claimed_today": "Sie haben bereits Ihr tägliches Einkommen abgeholt. Kommen Sie morgen um 22:00 UTC zurück."
    },
    // We'll add more languages similarly...
    pl: {
        "login": "Zaloguj się",
        "register": "Zarejestruj się",
        // ... continue for all keys
    },
    ru: {
        "login": "Войти",
        "register": "Регистрация",
        // ... continue for all keys
    },
    tr: {
        "login": "Giriş Yap",
        "register": "Kayıt Ol",
        // ... continue for all keys
    },
    ar: {
        "login": "تسجيل الدخول",
        "register": "تسجيل",
        // ... continue for all keys
    },
    ro: {
        "login": "Autentificare",
        "register": "Înregistrare",
        // ... continue for all keys
    },
    uk: {
        "login": "Увійти",
        "register": "Реєстрація",
        // ... continue for all keys
    },
    fr: {
        "login": "Connexion",
        "register": "Inscription",
        // ... continue for all keys
    },
    it: {
        "login": "Accedi",
        "register": "Registrati",
        // ... continue for all keys
    }
};

let currentLanguage = 'en';

function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('preferredLanguage', lang);
    applyTranslations();
    updateLanguageSelector();
}

function getLanguage() {
    return currentLanguage;
}

function applyTranslations() {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLanguage] && translations[currentLanguage][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[currentLanguage][key];
            } else {
                element.textContent = translations[currentLanguage][key];
            }
        }
    });
}

function updateLanguageSelector() {
    const selector = document.querySelector('.language-selector');
    if (selector) {
        const currentFlag = selector.querySelector('.current-flag');
        if (currentFlag) {
            currentFlag.textContent = getFlagEmoji(currentLanguage);
        }
    }
}

function getFlagEmoji(languageCode) {
    const flagMap = {
        'en': '🇺🇸',
        'es': '🇪🇸',
        'de': '🇩🇪',
        'pl': '🇵🇱',
        'ru': '🇷🇺',
        'tr': '🇹🇷',
        'ar': '🇸🇦',
        'ro': '🇷🇴',
        'uk': '🇺🇦',
        'fr': '🇫🇷',
        'it': '🇮🇹'
    };
    return flagMap[languageCode] || '🇺🇸';
}

function initializeLanguage() {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    const browserLanguage = navigator.language.split('-')[0];
    
    if (savedLanguage && translations[savedLanguage]) {
        setLanguage(savedLanguage);
    } else if (translations[browserLanguage]) {
        setLanguage(browserLanguage);
    } else {
        setLanguage('en');
    }
}

// Initialize when script loads
document.addEventListener('DOMContentLoaded', function() {
    initializeLanguage();
});

// Helper function for dynamic translations in JavaScript
function translate(key, params = {}) {
    let text = translations[currentLanguage] && translations[currentLanguage][key] 
        ? translations[currentLanguage][key] 
        : translations['en'][key] || key;
    
    // Replace parameters like {level} or {amount}
    Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
}
